// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package clients

import (
	"buf.build/gen/go/chain4travel/camino-messenger-protocol/grpc/go/cmp/services/ping/v1/pingv1grpc"
	"github.com/chain4travel/camino-messenger-bot/internal/messaging/types"

	"google.golang.org/grpc"
)

const (
	PingServiceV1                           = "cmp.services.ping.v1.PingService"
	PingServiceV1Request  types.MessageType = types.MessageType(PingServiceV1 + ".Request")
	PingServiceV1Response types.MessageType = types.MessageType(PingServiceV1 + ".Response")
)

var _ Client = (*PingClient)(nil)

func NewPingServiceV1(grpcCon *grpc.ClientConn) *PingClient {
	client := pingv1grpc.NewPingServiceClient(grpcCon)
	return &PingClient{client: &client}
}

type PingClient struct {
	client *pingv1grpc.PingServiceClient
}
