// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/v11/internal/matrix/messenger (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package=messenger -destination=internal/matrix/messenger/mock_client.go github.com/chain4travel/camino-messenger-bot/v11/internal/matrix/messenger Client
//

// Package messenger is a generated GoMock package.
package messenger

import (
	context "context"
	reflect "reflect"

	matrix "github.com/chain4travel/camino-messenger-bot/v11/pkg/matrix"
	gomock "go.uber.org/mock/gomock"
	event "maunium.net/go/mautrix/event"
	id "maunium.net/go/mautrix/id"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// CreateRoomForUser mocks base method.
func (m *MockClient) CreateRoomForUser(arg0 context.Context, arg1 id.UserID) (id.RoomID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoomForUser", arg0, arg1)
	ret0, _ := ret[0].(id.RoomID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoomForUser indicates an expected call of CreateRoomForUser.
func (mr *MockClientMockRecorder) CreateRoomForUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoomForUser", reflect.TypeOf((*MockClient)(nil).CreateRoomForUser), arg0, arg1)
}

// EnableRoomEncryption mocks base method.
func (m *MockClient) EnableRoomEncryption(arg0 context.Context, arg1 id.RoomID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableRoomEncryption", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableRoomEncryption indicates an expected call of EnableRoomEncryption.
func (mr *MockClientMockRecorder) EnableRoomEncryption(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableRoomEncryption", reflect.TypeOf((*MockClient)(nil).EnableRoomEncryption), arg0, arg1)
}

// IsRoomEncrypted mocks base method.
func (m *MockClient) IsRoomEncrypted(arg0 context.Context, arg1 id.RoomID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRoomEncrypted", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRoomEncrypted indicates an expected call of IsRoomEncrypted.
func (mr *MockClientMockRecorder) IsRoomEncrypted(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRoomEncrypted", reflect.TypeOf((*MockClient)(nil).IsRoomEncrypted), arg0, arg1)
}

// IsUserJoinedRoom mocks base method.
func (m *MockClient) IsUserJoinedRoom(arg0 context.Context, arg1 id.RoomID, arg2 id.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserJoinedRoom", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserJoinedRoom indicates an expected call of IsUserJoinedRoom.
func (mr *MockClientMockRecorder) IsUserJoinedRoom(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserJoinedRoom", reflect.TypeOf((*MockClient)(nil).IsUserJoinedRoom), arg0, arg1, arg2)
}

// JoinRoom mocks base method.
func (m *MockClient) JoinRoom(arg0 context.Context, arg1 id.RoomID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinRoom", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinRoom indicates an expected call of JoinRoom.
func (mr *MockClientMockRecorder) JoinRoom(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinRoom", reflect.TypeOf((*MockClient)(nil).JoinRoom), arg0, arg1)
}

// JoinedRooms mocks base method.
func (m *MockClient) JoinedRooms(arg0 context.Context) ([]id.RoomID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinedRooms", arg0)
	ret0, _ := ret[0].([]id.RoomID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinedRooms indicates an expected call of JoinedRooms.
func (mr *MockClientMockRecorder) JoinedRooms(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinedRooms", reflect.TypeOf((*MockClient)(nil).JoinedRooms), arg0)
}

// SendMessageEvent mocks base method.
func (m *MockClient) SendMessageEvent(arg0 context.Context, arg1 id.RoomID, arg2 event.Type, arg3 matrix.CaminoMatrixMessageEventContent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageEvent", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageEvent indicates an expected call of SendMessageEvent.
func (mr *MockClientMockRecorder) SendMessageEvent(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageEvent", reflect.TypeOf((*MockClient)(nil).SendMessageEvent), arg0, arg1, arg2, arg3)
}

// SetEventHandler mocks base method.
func (m *MockClient) SetEventHandler(arg0 event.Type, arg1 func(context.Context, *event.Event)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEventHandler", arg0, arg1)
}

// SetEventHandler indicates an expected call of SetEventHandler.
func (mr *MockClientMockRecorder) SetEventHandler(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEventHandler", reflect.TypeOf((*MockClient)(nil).SetEventHandler), arg0, arg1)
}

// SyncWithContext mocks base method.
func (m *MockClient) SyncWithContext(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncWithContext", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncWithContext indicates an expected call of SyncWithContext.
func (mr *MockClientMockRecorder) SyncWithContext(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncWithContext", reflect.TypeOf((*MockClient)(nil).SyncWithContext), arg0)
}
