// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: readiness/readiness.proto

package readiness

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ReadinessService_Readiness_FullMethodName = "/readiness.ReadinessService/Readiness"
)

// ReadinessServiceClient is the client API for ReadinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReadinessServiceClient interface {
	Readiness(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadinessResponse, error)
}

type readinessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReadinessServiceClient(cc grpc.ClientConnInterface) ReadinessServiceClient {
	return &readinessServiceClient{cc}
}

func (c *readinessServiceClient) Readiness(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadinessResponse, error) {
	out := new(ReadinessResponse)
	err := c.cc.Invoke(ctx, ReadinessService_Readiness_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadinessServiceServer is the server API for ReadinessService service.
// All implementations must embed UnimplementedReadinessServiceServer
// for forward compatibility
type ReadinessServiceServer interface {
	Readiness(context.Context, *emptypb.Empty) (*ReadinessResponse, error)
	mustEmbedUnimplementedReadinessServiceServer()
}

// UnimplementedReadinessServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReadinessServiceServer struct {
}

func (UnimplementedReadinessServiceServer) Readiness(context.Context, *emptypb.Empty) (*ReadinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Readiness not implemented")
}
func (UnimplementedReadinessServiceServer) mustEmbedUnimplementedReadinessServiceServer() {}

// UnsafeReadinessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadinessServiceServer will
// result in compilation errors.
type UnsafeReadinessServiceServer interface {
	mustEmbedUnimplementedReadinessServiceServer()
}

func RegisterReadinessServiceServer(s grpc.ServiceRegistrar, srv ReadinessServiceServer) {
	s.RegisterService(&ReadinessService_ServiceDesc, srv)
}

func _ReadinessService_Readiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadinessServiceServer).Readiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadinessService_Readiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadinessServiceServer).Readiness(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ReadinessService_ServiceDesc is the grpc.ServiceDesc for ReadinessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReadinessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "readiness.ReadinessService",
	HandlerType: (*ReadinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Readiness",
			Handler:    _ReadinessService_Readiness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "readiness/readiness.proto",
}
