# https://golangci-lint.run/usage/configuration/
version: "2"
run:
  relative-path-mode: gomod
  build-tags:
    - e2e
  modules-download-mode: readonly
  timeout: 5m
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        packages:
          deny:
            - pkg: io/ioutil
              desc: io/ioutil is deprecated. Use package io or os instead.
            - pkg: github.com/stretchr/testify/assert
              desc: github.com/stretchr/testify/require should be used instead.
            - pkg: github.com/golang/mock/gomock
              desc: go.uber.org/mock/gomock should be used instead.
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - camino-matrix-go
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - camino-matrix-go
      - third_party$
      - builtin$
      - examples$
