version: "3"
services:
  bot:
    image: c4tplatform/camino-messenger-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cmb-config:/cmb-config
    ports:
      - "9090:9090"
    command: ["--config", "/cmb-config/config.yaml"]
  provider-plugin:
    image: c4tplatform/camino-messenger-bot-plugin
    build:
      context: .
      dockerfile: Dockerfile.plugin
      args:
        port: 50052
    ports:
      - "50052:50052"
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
