version: "3"
services:
  supplier-bot:
    image: c4tplatform/camino-messenger-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CMB_DEVELOPER_MODE: "true"
      CMB_MATRIX_KEY: "PRIVATE_KEY_HEX"
      CMB_MATRIX_HOST: "matrix.camino.network"
      CMB_MATRIX_STORE: "supplier-matrix.db"
      CMB_RPC_SERVER_PORT: "9090"
      CMB_RPC_UNENCRYPTED: "true"
      CMB_PARTNER_PLUGIN_HOST: "localhost"
      CMB_PARTNER_PLUGIN_PORT: "50051"
      CMB_PARTNER_PLUGIN_UNENCRYPTED: "true"
      CMB_RESPONSE_TIMEOUT: "10000"
      CMB_SUPPORTED_REQUEST_TYPES: "GetNetworkFeeRequest,GetPartnerConfigurationRequest,PingRequest,AccommodationProductListRequest,AccommodationProductInfoRequest,AccommodationSearchRequest,ActivityProductListRequest,ActivityProductInfoRequest,ActivitySearchRequest,TransportSearchRequest,MintRequest,ValidationRequest,SeatMapRequest,SeatMapAvailabilityRequest,CountryEntryRequirementsRequest"
      CMB_RPC_URL: "https://columbus.camino.network/ext/bc/C/rpc"
      CMB_BOOKING_TOKEN_ABI_FILE: abi/BookingTokenV0.abi
      CMB_SUPPLIER_NAME: SUPPLIER_NAME
      CMB_EVM_PRIVATE_KEY: "PRIVATE_KEY_HEX"
      CMB_BUYABLE_UNTIL_DEFAULT: "600"
    ports:
      - "9090:9090"
  distributor-bot:
    image: c4tplatform/camino-messenger-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CMB_DEVELOPER_MODE: "true"
      CMB_MATRIX_KEY: "PRIVATE_KEY_HEX"
      CMB_MATRIX_HOST: "matrix.camino.network"
      CMB_MATRIX_STORE: "distributor-matrix.db"
      CMB_RPC_SERVER_PORT: "9090"
      CMB_RPC_UNENCRYPTED: "true"
      CMB_RESPONSE_TIMEOUT: "10000"
      CMB_SUPPORTED_REQUEST_TYPES: "GetNetworkFeeRequest,GetPartnerConfigurationRequest,PingRequest"
      CMB_RPC_URL: "https://columbus.camino.network/ext/bc/C/rpc"
      CMB_BOOKING_TOKEN_ABI_FILE: "abi/BookingTokenV0.abi"
      CMB_EVM_PRIVATE_KEY: "PRIVATE_KEY_HEX"
    ports:
      - "9092:9090"
  provider-plugin:
    image: c4tplatform/camino-messenger-bot-plugin
    build:
      context: .
      dockerfile: Dockerfile.plugin
      args:
        port: 50052
    ports:
      - "50052:50052"
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
