FROM golang:1.24.9-alpine AS build-stage
RUN apk update && apk upgrade && apk add build-base

WORKDIR /camino-messenger-bot

COPY . .
RUN apk --no-cache add bash
RUN CAMINOBOT_PATH=$(pwd) bash ./scripts/build_partner_plugin_mock.sh


#runtime stage
FROM alpine:3.21 AS runtime-stage

WORKDIR /

ARG port=55555
COPY --from=build-stage /camino-messenger-bot/build/pp-mock /pp-mock
ENV CMB_PARTNER_PLUGIN_MOCK_PORT=$port

# Run the 'env' command

#EXPOSE $port

ENTRYPOINT [ "./pp-mock" ]