FROM golang:1.20-alpine3.18 AS build-stage
RUN apk update && apk upgrade && apk add build-base

WORKDIR /camino-messenger-bot

COPY . .
RUN go mod download
RUN go build -o plugin  examples/rpc/partner-plugin/server.go


#runtime stage
FROM alpine:3.18 AS runtime-stage

WORKDIR /

ARG port=55555
COPY --from=build-stage /camino-messenger-bot/plugin /plugin
ENV PORT=$port

# Run the 'env' command

#EXPOSE $port

ENTRYPOINT [ "./plugin" ]