version: '3'
services:
  provider-bot:
    image: c4tplatform/camino-messenger-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CMB_DEVELOPER_MODE: "true"
      CMB_MATRIX_KEY: "PrivateKey-THE_REST_OF_THE_KEY"
      CMB_MATRIX_HOST: "matrix.camino.network"
      CMB_MATRIX_STORE: "mautrix-localhost.db"
      CMB_RPC_SERVER_PORT: "9090"
      CMB_RPC_UNENCRYPTED: 'true'
      CMB_PARTNER_PLUGIN_HOST: "localhost"
      CMB_PARTNER_PLUGIN_PORT: "50051"
      CMB_PARTNER_PLUGIN_UNENCRYPTED: "true"
      CMB_RESPONSE_TIMEOUT: "3000"
      CMB_SUPPORTED_REQUEST_TYPES: "ActivitySearchRequest,AccommodationSearchRequest,GetNetworkFeeRequest,GetPartnerConfigurationRequest,PingRequest,TransportSearchRequest"
    ports:
      - "9090:9090"
  distributor-bot:
    image: c4tplatform/camino-messenger-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CMB_DEVELOPER_MODE: "true"
      CMB_MATRIX_KEY: "PrivateKey-THE_REST_OF_THE_KEY"
      CMB_MATRIX_HOST: "matrix.camino.network"
      CMB_MATRIX_STORE: "mautrix-localhost.db"
      CMB_RPC_SERVER_PORT: "9090"
      CMB_RPC_UNENCRYPTED: "true"
      CMB_PARTNER_PLUGIN_HOST: "localhost"
      CMB_PARTNER_PLUGIN_PORT: "50052"
      CMB_PARTNER_PLUGIN_UNENCRYPTED: "true"
      CMB_RESPONSE_TIMEOUT: "3000"
      CMB_SUPPORTED_REQUEST_TYPES: "ActivitySearchRequest,AccommodationSearchRequest,GetNetworkFeeRequest,GetPartnerConfigurationRequest,PingRequest,TransportSearchRequest"
    ports:
      - "9092:9090"
  provider-plugin:
    image: c4tplatform/camino-messenger-bot-plugin
    build:
      context: .
      dockerfile: Dockerfile.plugin
      args:
        port: 50052
    ports:
      - "50052:50052"
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug