// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/v13/pkg/cm_accounts (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=cmaccounts -destination=pkg/cm_accounts/mock_cm_accounts.go github.com/chain4travel/camino-messenger-bot/v13/pkg/cm_accounts Service
//

// Package cmaccounts is a generated GoMock package.
package cmaccounts

import (
	context "context"
	ecdsa "crypto/ecdsa"
	big "math/big"
	reflect "reflect"

	cheques "github.com/chain4travel/camino-messenger-bot/v13/pkg/cheques"
	cmaccount "github.com/chain4travel/camino-messenger-contracts/go/contracts/cmaccount"
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind/v2"
	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AcceptCancellationProposal mocks base method.
func (m *MockService) AcceptCancellationProposal(arg0 context.Context, arg1 *ecdsa.PrivateKey, arg2 common.Address, arg3, arg4 *big.Int) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptCancellationProposal", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptCancellationProposal indicates an expected call of AcceptCancellationProposal.
func (mr *MockServiceMockRecorder) AcceptCancellationProposal(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptCancellationProposal", reflect.TypeOf((*MockService)(nil).AcceptCancellationProposal), arg0, arg1, arg2, arg3, arg4)
}

// BuyBookingToken mocks base method.
func (m *MockService) BuyBookingToken(arg0 context.Context, arg1 *bind.TransactOpts, arg2 common.Address, arg3, arg4 *big.Int, arg5 common.Address) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuyBookingToken", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuyBookingToken indicates an expected call of BuyBookingToken.
func (mr *MockServiceMockRecorder) BuyBookingToken(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuyBookingToken", reflect.TypeOf((*MockService)(nil).BuyBookingToken), arg0, arg1, arg2, arg3, arg4, arg5)
}

// CMAccount mocks base method.
func (m *MockService) CMAccount(arg0 common.Address) (*cmaccount.Cmaccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CMAccount", arg0)
	ret0, _ := ret[0].(*cmaccount.Cmaccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CMAccount indicates an expected call of CMAccount.
func (mr *MockServiceMockRecorder) CMAccount(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CMAccount", reflect.TypeOf((*MockService)(nil).CMAccount), arg0)
}

// CashInCheque mocks base method.
func (m *MockService) CashInCheque(arg0 context.Context, arg1 *cheques.SignedCheque, arg2 *ecdsa.PrivateKey) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CashInCheque", arg0, arg1, arg2)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CashInCheque indicates an expected call of CashInCheque.
func (mr *MockServiceMockRecorder) CashInCheque(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CashInCheque", reflect.TypeOf((*MockService)(nil).CashInCheque), arg0, arg1, arg2)
}

// CounterCancellation mocks base method.
func (m *MockService) CounterCancellation(arg0 context.Context, arg1 *ecdsa.PrivateKey, arg2 common.Address, arg3, arg4 *big.Int, arg5, arg6 uint16) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CounterCancellation", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CounterCancellation indicates an expected call of CounterCancellation.
func (mr *MockServiceMockRecorder) CounterCancellation(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CounterCancellation", reflect.TypeOf((*MockService)(nil).CounterCancellation), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// FinalizeCancellation mocks base method.
func (m *MockService) FinalizeCancellation(arg0 context.Context, arg1 *ecdsa.PrivateKey, arg2 common.Address, arg3, arg4 *big.Int) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeCancellation", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeCancellation indicates an expected call of FinalizeCancellation.
func (mr *MockServiceMockRecorder) FinalizeCancellation(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeCancellation", reflect.TypeOf((*MockService)(nil).FinalizeCancellation), arg0, arg1, arg2, arg3, arg4)
}

// GetAllChequeOperators mocks base method.
func (m *MockService) GetAllChequeOperators(arg0 context.Context, arg1 common.Address) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllChequeOperators", arg0, arg1)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllChequeOperators indicates an expected call of GetAllChequeOperators.
func (mr *MockServiceMockRecorder) GetAllChequeOperators(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllChequeOperators", reflect.TypeOf((*MockService)(nil).GetAllChequeOperators), arg0, arg1)
}

// GetLastCashIn mocks base method.
func (m *MockService) GetLastCashIn(arg0 context.Context, arg1, arg2, arg3, arg4 common.Address) (*big.Int, *big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCashIn", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(*big.Int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLastCashIn indicates an expected call of GetLastCashIn.
func (mr *MockServiceMockRecorder) GetLastCashIn(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCashIn", reflect.TypeOf((*MockService)(nil).GetLastCashIn), arg0, arg1, arg2, arg3, arg4)
}

// GetServiceFee mocks base method.
func (m *MockService) GetServiceFee(arg0 context.Context, arg1 common.Address, arg2 string) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceFee", arg0, arg1, arg2)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceFee indicates an expected call of GetServiceFee.
func (mr *MockServiceMockRecorder) GetServiceFee(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceFee", reflect.TypeOf((*MockService)(nil).GetServiceFee), arg0, arg1, arg2)
}

// GetServiceFeeToken mocks base method.
func (m *MockService) GetServiceFeeToken(arg0 context.Context, arg1 common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceFeeToken", arg0, arg1)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceFeeToken indicates an expected call of GetServiceFeeToken.
func (mr *MockServiceMockRecorder) GetServiceFeeToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceFeeToken", reflect.TypeOf((*MockService)(nil).GetServiceFeeToken), arg0, arg1)
}

// InitiateCancellationProposal mocks base method.
func (m *MockService) InitiateCancellationProposal(arg0 context.Context, arg1 *ecdsa.PrivateKey, arg2 common.Address, arg3, arg4 *big.Int, arg5, arg6 uint16) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateCancellationProposal", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateCancellationProposal indicates an expected call of InitiateCancellationProposal.
func (mr *MockServiceMockRecorder) InitiateCancellationProposal(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateCancellationProposal", reflect.TypeOf((*MockService)(nil).InitiateCancellationProposal), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// IsCMAccountImplementationUpToDate mocks base method.
func (m *MockService) IsCMAccountImplementationUpToDate(arg0 context.Context, arg1 common.Address) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCMAccountImplementationUpToDate", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCMAccountImplementationUpToDate indicates an expected call of IsCMAccountImplementationUpToDate.
func (mr *MockServiceMockRecorder) IsCMAccountImplementationUpToDate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCMAccountImplementationUpToDate", reflect.TypeOf((*MockService)(nil).IsCMAccountImplementationUpToDate), arg0, arg1)
}

// MintBookingToken mocks base method.
func (m *MockService) MintBookingToken(arg0 context.Context, arg1 *bind.TransactOpts, arg2, arg3 common.Address, arg4 string, arg5, arg6 *big.Int, arg7 common.Address, arg8 *big.Int, arg9 bool) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MintBookingToken", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MintBookingToken indicates an expected call of MintBookingToken.
func (mr *MockServiceMockRecorder) MintBookingToken(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MintBookingToken", reflect.TypeOf((*MockService)(nil).MintBookingToken), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
}

// RecordExpiration mocks base method.
func (m *MockService) RecordExpiration(arg0 context.Context, arg1 *bind.TransactOpts, arg2 common.Address, arg3 *big.Int) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordExpiration", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordExpiration indicates an expected call of RecordExpiration.
func (mr *MockServiceMockRecorder) RecordExpiration(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordExpiration", reflect.TypeOf((*MockService)(nil).RecordExpiration), arg0, arg1, arg2, arg3)
}

// RejectCancellationProposal mocks base method.
func (m *MockService) RejectCancellationProposal(arg0 context.Context, arg1 *ecdsa.PrivateKey, arg2 common.Address, arg3 *big.Int, arg4, arg5 uint16) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectCancellationProposal", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RejectCancellationProposal indicates an expected call of RejectCancellationProposal.
func (mr *MockServiceMockRecorder) RejectCancellationProposal(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectCancellationProposal", reflect.TypeOf((*MockService)(nil).RejectCancellationProposal), arg0, arg1, arg2, arg3, arg4, arg5)
}

// VerifyCheque mocks base method.
func (m *MockService) VerifyCheque(arg0 context.Context, arg1 *cheques.SignedCheque) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCheque", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyCheque indicates an expected call of VerifyCheque.
func (mr *MockServiceMockRecorder) VerifyCheque(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCheque", reflect.TypeOf((*MockService)(nil).VerifyCheque), arg0, arg1)
}

// WithdrawCancellation mocks base method.
func (m *MockService) WithdrawCancellation(arg0 context.Context, arg1 *ecdsa.PrivateKey, arg2 common.Address, arg3 *big.Int, arg4, arg5 uint16) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawCancellation", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithdrawCancellation indicates an expected call of WithdrawCancellation.
func (mr *MockServiceMockRecorder) WithdrawCancellation(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawCancellation", reflect.TypeOf((*MockService)(nil).WithdrawCancellation), arg0, arg1, arg2, arg3, arg4, arg5)
}
