// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"{{GRPC_INC}}"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/rpc"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/messaging/message"

	"google.golang.org/grpc"
)

const (
	{{SERVICE}}ServiceV{{VERSION}} = "{{FQPN}}"
	{{SERVICE}}ServiceV{{VERSION}}Request  message.Type = message.Type({{SERVICE}}ServiceV{{VERSION}} + ".Request")
	{{SERVICE}}ServiceV{{VERSION}}Response message.Type = message.Type({{SERVICE}}ServiceV{{VERSION}} + ".Response")
)

var _ rpc.Client = (*{{SERVICE}}V{{VERSION}}Client)(nil)

func New{{SERVICE}}ServiceV{{VERSION}}Client(grpcCon *grpc.ClientConn) *{{SERVICE}}V{{VERSION}}Client {
	client := {{GRPC_PACKAGE}}.New{{SERVICE}}ServiceClient(grpcCon)
	return &{{SERVICE}}V{{VERSION}}Client{client: client}
}

type {{SERVICE}}V{{VERSION}}Client struct {
	client {{GRPC_PACKAGE}}.{{SERVICE}}ServiceClient
}
