// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"context"
	"fmt"

	{{TYPE_PACKAGE}} "{{PROTO_INC}}"
	typesv{{COMMON_TYPES_VERSION}} "buf.build/gen/go/chain4travel/camino-messenger-protocol/protocolbuffers/go/cmp/types/v{{COMMON_TYPES_VERSION}}"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/messaging/types"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/rpc"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/version"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func (s {{SERVICE}}V{{VERSION}}Client) Call(ctx context.Context, requestIntf protoreflect.ProtoMessage, opts ...grpc.CallOption) (protoreflect.ProtoMessage, types.MessageType) {
	messageType := {{SERVICE}}V{{VERSION}}Response

	request, ok := requestIntf.(*{{TYPE_PACKAGE}}.{{REQUEST}})
	if !ok {
		return s.errorResponse(fmt.Sprintf("invalid request type: expected %s, got %T", {{SERVICE}}V{{VERSION}}Request, requestIntf)), messageType
	}
	
	response, err := s.client.{{METHOD}}(ctx, request, opts...)
	if err != nil {
		return s.errorResponse(err.Error()), messageType
	}

	if response.HasErrorResponse() {
		innerResp := response.GetErrorResponse()
		if innerResp.GetHeader().GetBaseHeader() == nil {
			return s.errorResponse(rpc.ErrNilResponseHeader.Error()), messageType
		}
		innerResp.Header.BaseHeader.Version = version.VersionV4
	} else {
		innerResp := response.GetSuccessResponse()
		if innerResp.GetHeader().GetBaseHeader() == nil {
			return s.errorResponse(rpc.ErrNilResponseHeader.Error()), messageType
		}
		innerResp.Header.BaseHeader.Version = version.VersionV4
	}

	if err := protovalidate.Validate(response); err != nil {
		return s.errorResponse(fmt.Sprintf("response validation failed: %v", err)), messageType
	}

	return response, messageType
}

func (s *{{SERVICE}}V{{VERSION}}Client) ErrorResponseAndType(errorMessage string) (protoreflect.ProtoMessage, types.MessageType) {
	return s.errorResponse(errorMessage), {{SERVICE}}V{{VERSION}}Response
}

func (s *{{SERVICE}}V{{VERSION}}Client) errorResponse(errorMessage string) protoreflect.ProtoMessage {
	return &{{TYPE_PACKAGE}}.{{RESPONSE}}{
		Response: &{{TYPE_PACKAGE}}.{{RESPONSE}}_ErrorResponse{
			ErrorResponse: &{{TYPE_PACKAGE}}.{{SERVICE}}ErrorResponse{
				Header: &typesv{{COMMON_TYPES_VERSION}}.ErrorResponseHeader{
					BaseHeader: &typesv{{COMMON_TYPES_VERSION}}.Header{Version: version.VersionV{{COMMON_TYPES_VERSION}}},
					Errors:     []*typesv{{COMMON_TYPES_VERSION}}.Error{{Message: errorMessage}},
				},
			},
		},
	}
}
