// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/internal/partnerplugin (interfaces: PartnerPlugin)
//
// Generated by this command:
//
//	mockgen -package=partnerplugin -destination=internal/partnerplugin/mock_partner_plugin.go github.com/chain4travel/camino-messenger-bot/internal/partnerplugin PartnerPlugin
//

// Package partnerplugin is a generated GoMock package.
package partnerplugin

import (
	context "context"
	big "math/big"
	reflect "reflect"

	types "github.com/chain4travel/camino-messenger-bot/internal/messaging/types"
	rpc "github.com/chain4travel/camino-messenger-bot/internal/rpc"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockPartnerPlugin is a mock of PartnerPlugin interface.
type MockPartnerPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerPluginMockRecorder
}

// MockPartnerPluginMockRecorder is the mock recorder for MockPartnerPlugin.
type MockPartnerPluginMockRecorder struct {
	mock *MockPartnerPlugin
}

// NewMockPartnerPlugin creates a new mock instance.
func NewMockPartnerPlugin(ctrl *gomock.Controller) *MockPartnerPlugin {
	mock := &MockPartnerPlugin{ctrl: ctrl}
	mock.recorder = &MockPartnerPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerPlugin) EXPECT() *MockPartnerPluginMockRecorder {
	return m.recorder
}

// DoServiceRequest mocks base method.
func (m *MockPartnerPlugin) DoServiceRequest(arg0 context.Context, arg1 *types.Message, arg2 rpc.Client) (context.Context, *types.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoServiceRequest", arg0, arg1, arg2)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(*types.Message)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DoServiceRequest indicates an expected call of DoServiceRequest.
func (mr *MockPartnerPluginMockRecorder) DoServiceRequest(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoServiceRequest", reflect.TypeOf((*MockPartnerPlugin)(nil).DoServiceRequest), arg0, arg1, arg2)
}

// SendTokenBoughtNotification mocks base method.
func (m *MockPartnerPlugin) SendTokenBoughtNotification(arg0 context.Context, arg1 *big.Int, arg2 string, arg3 common.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTokenBoughtNotification", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTokenBoughtNotification indicates an expected call of SendTokenBoughtNotification.
func (mr *MockPartnerPluginMockRecorder) SendTokenBoughtNotification(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTokenBoughtNotification", reflect.TypeOf((*MockPartnerPlugin)(nil).SendTokenBoughtNotification), arg0, arg1, arg2, arg3)
}

// SendTokenExpiredNotification mocks base method.
func (m *MockPartnerPlugin) SendTokenExpiredNotification(arg0 context.Context, arg1 *big.Int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTokenExpiredNotification", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTokenExpiredNotification indicates an expected call of SendTokenExpiredNotification.
func (mr *MockPartnerPluginMockRecorder) SendTokenExpiredNotification(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTokenExpiredNotification", reflect.TypeOf((*MockPartnerPlugin)(nil).SendTokenExpiredNotification), arg0, arg1, arg2)
}
