// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/v13/internal/partnerplugin (interfaces: PartnerPlugin)
//
// Generated by this command:
//
//	mockgen -package=partnerplugin -destination=internal/partnerplugin/mock_partner_plugin.go github.com/chain4travel/camino-messenger-bot/v13/internal/partnerplugin PartnerPlugin
//

// Package partnerplugin is a generated GoMock package.
package partnerplugin

import (
	context "context"
	big "math/big"
	reflect "reflect"

	notificationv3 "buf.build/gen/go/chain4travel/camino-messenger-protocol/protocolbuffers/go/cmp/services/notification/v3"
	message "github.com/chain4travel/camino-messenger-bot/v13/internal/messaging/message"
	rpc "github.com/chain4travel/camino-messenger-bot/v13/internal/rpc"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// MockPartnerPlugin is a mock of PartnerPlugin interface.
type MockPartnerPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerPluginMockRecorder
}

// MockPartnerPluginMockRecorder is the mock recorder for MockPartnerPlugin.
type MockPartnerPluginMockRecorder struct {
	mock *MockPartnerPlugin
}

// NewMockPartnerPlugin creates a new mock instance.
func NewMockPartnerPlugin(ctrl *gomock.Controller) *MockPartnerPlugin {
	mock := &MockPartnerPlugin{ctrl: ctrl}
	mock.recorder = &MockPartnerPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerPlugin) EXPECT() *MockPartnerPluginMockRecorder {
	return m.recorder
}

// CancellationFinalizedNotification mocks base method.
func (m *MockPartnerPlugin) CancellationFinalizedNotification(arg0 context.Context, arg1 *notificationv3.CancellationFinalized) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancellationFinalizedNotification", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancellationFinalizedNotification indicates an expected call of CancellationFinalizedNotification.
func (mr *MockPartnerPluginMockRecorder) CancellationFinalizedNotification(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancellationFinalizedNotification", reflect.TypeOf((*MockPartnerPlugin)(nil).CancellationFinalizedNotification), arg0, arg1)
}

// CancellationPendingNotification mocks base method.
func (m *MockPartnerPlugin) CancellationPendingNotification(arg0 context.Context, arg1 *notificationv3.CancellationPending) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancellationPendingNotification", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancellationPendingNotification indicates an expected call of CancellationPendingNotification.
func (mr *MockPartnerPluginMockRecorder) CancellationPendingNotification(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancellationPendingNotification", reflect.TypeOf((*MockPartnerPlugin)(nil).CancellationPendingNotification), arg0, arg1)
}

// CancellationRejectedNotification mocks base method.
func (m *MockPartnerPlugin) CancellationRejectedNotification(arg0 context.Context, arg1 *notificationv3.CancellationRejected) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancellationRejectedNotification", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancellationRejectedNotification indicates an expected call of CancellationRejectedNotification.
func (mr *MockPartnerPluginMockRecorder) CancellationRejectedNotification(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancellationRejectedNotification", reflect.TypeOf((*MockPartnerPlugin)(nil).CancellationRejectedNotification), arg0, arg1)
}

// CancellationWithdrawnNotification mocks base method.
func (m *MockPartnerPlugin) CancellationWithdrawnNotification(arg0 context.Context, arg1 *notificationv3.CancellationWithdrawn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancellationWithdrawnNotification", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancellationWithdrawnNotification indicates an expected call of CancellationWithdrawnNotification.
func (mr *MockPartnerPluginMockRecorder) CancellationWithdrawnNotification(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancellationWithdrawnNotification", reflect.TypeOf((*MockPartnerPlugin)(nil).CancellationWithdrawnNotification), arg0, arg1)
}

// DoServiceRequest mocks base method.
func (m *MockPartnerPlugin) DoServiceRequest(arg0 context.Context, arg1 *message.Message, arg2 rpc.Client, arg3, arg4 common.Address) (protoreflect.ProtoMessage, message.Type) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoServiceRequest", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(protoreflect.ProtoMessage)
	ret1, _ := ret[1].(message.Type)
	return ret0, ret1
}

// DoServiceRequest indicates an expected call of DoServiceRequest.
func (mr *MockPartnerPluginMockRecorder) DoServiceRequest(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoServiceRequest", reflect.TypeOf((*MockPartnerPlugin)(nil).DoServiceRequest), arg0, arg1, arg2, arg3, arg4)
}

// TokenBoughtNotificationWithBuyTx mocks base method.
func (m *MockPartnerPlugin) TokenBoughtNotificationWithBuyTx(arg0 context.Context, arg1 *big.Int, arg2 string, arg3 common.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenBoughtNotificationWithBuyTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// TokenBoughtNotificationWithBuyTx indicates an expected call of TokenBoughtNotificationWithBuyTx.
func (mr *MockPartnerPluginMockRecorder) TokenBoughtNotificationWithBuyTx(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenBoughtNotificationWithBuyTx", reflect.TypeOf((*MockPartnerPlugin)(nil).TokenBoughtNotificationWithBuyTx), arg0, arg1, arg2, arg3)
}

// TokenBoughtNotificationWithoutBuyTx mocks base method.
func (m *MockPartnerPlugin) TokenBoughtNotificationWithoutBuyTx(arg0 context.Context, arg1 *big.Int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenBoughtNotificationWithoutBuyTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TokenBoughtNotificationWithoutBuyTx indicates an expected call of TokenBoughtNotificationWithoutBuyTx.
func (mr *MockPartnerPluginMockRecorder) TokenBoughtNotificationWithoutBuyTx(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenBoughtNotificationWithoutBuyTx", reflect.TypeOf((*MockPartnerPlugin)(nil).TokenBoughtNotificationWithoutBuyTx), arg0, arg1, arg2)
}

// TokenExpiredNotification mocks base method.
func (m *MockPartnerPlugin) TokenExpiredNotification(arg0 context.Context, arg1 *big.Int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenExpiredNotification", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TokenExpiredNotification indicates an expected call of TokenExpiredNotification.
func (mr *MockPartnerPluginMockRecorder) TokenExpiredNotification(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenExpiredNotification", reflect.TypeOf((*MockPartnerPlugin)(nil).TokenExpiredNotification), arg0, arg1, arg2)
}
