// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/v11/internal/partnerplugin (interfaces: PartnerPlugin)
//
// Generated by this command:
//
//	mockgen -package=partnerplugin -destination=internal/partnerplugin/mock_partner_plugin.go github.com/chain4travel/camino-messenger-bot/v11/internal/partnerplugin PartnerPlugin
//

// Package partnerplugin is a generated GoMock package.
package partnerplugin

import (
	context "context"
	big "math/big"
	reflect "reflect"

	types "github.com/chain4travel/camino-messenger-bot/v11/internal/messaging/types"
	rpc "github.com/chain4travel/camino-messenger-bot/v11/internal/rpc"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockPartnerPlugin is a mock of PartnerPlugin interface.
type MockPartnerPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerPluginMockRecorder
}

// MockPartnerPluginMockRecorder is the mock recorder for MockPartnerPlugin.
type MockPartnerPluginMockRecorder struct {
	mock *MockPartnerPlugin
}

// NewMockPartnerPlugin creates a new mock instance.
func NewMockPartnerPlugin(ctrl *gomock.Controller) *MockPartnerPlugin {
	mock := &MockPartnerPlugin{ctrl: ctrl}
	mock.recorder = &MockPartnerPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerPlugin) EXPECT() *MockPartnerPluginMockRecorder {
	return m.recorder
}

// DoServiceRequest mocks base method.
func (m *MockPartnerPlugin) DoServiceRequest(arg0 context.Context, arg1 *types.Message, arg2 rpc.Client) (context.Context, *types.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoServiceRequest", arg0, arg1, arg2)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(*types.Message)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DoServiceRequest indicates an expected call of DoServiceRequest.
func (mr *MockPartnerPluginMockRecorder) DoServiceRequest(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoServiceRequest", reflect.TypeOf((*MockPartnerPlugin)(nil).DoServiceRequest), arg0, arg1, arg2)
}

// TokenBoughtNotificationWithBuyTx mocks base method.
func (m *MockPartnerPlugin) TokenBoughtNotificationWithBuyTx(arg0 context.Context, arg1 *big.Int, arg2 string, arg3 common.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenBoughtNotificationWithBuyTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// TokenBoughtNotificationWithBuyTx indicates an expected call of TokenBoughtNotificationWithBuyTx.
func (mr *MockPartnerPluginMockRecorder) TokenBoughtNotificationWithBuyTx(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenBoughtNotificationWithBuyTx", reflect.TypeOf((*MockPartnerPlugin)(nil).TokenBoughtNotificationWithBuyTx), arg0, arg1, arg2, arg3)
}

// TokenBoughtNotificationWithoutBuyTx mocks base method.
func (m *MockPartnerPlugin) TokenBoughtNotificationWithoutBuyTx(arg0 context.Context, arg1 *big.Int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenBoughtNotificationWithoutBuyTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TokenBoughtNotificationWithoutBuyTx indicates an expected call of TokenBoughtNotificationWithoutBuyTx.
func (mr *MockPartnerPluginMockRecorder) TokenBoughtNotificationWithoutBuyTx(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenBoughtNotificationWithoutBuyTx", reflect.TypeOf((*MockPartnerPlugin)(nil).TokenBoughtNotificationWithoutBuyTx), arg0, arg1, arg2)
}

// TokenExpiredNotification mocks base method.
func (m *MockPartnerPlugin) TokenExpiredNotification(arg0 context.Context, arg1 *big.Int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenExpiredNotification", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TokenExpiredNotification indicates an expected call of TokenExpiredNotification.
func (mr *MockPartnerPluginMockRecorder) TokenExpiredNotification(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenExpiredNotification", reflect.TypeOf((*MockPartnerPlugin)(nil).TokenExpiredNotification), arg0, arg1, arg2)
}
