# This example is made for development purposes - for production see docker-compose.yml

# Lower level logging for local development
developer_mode: true

### Tracing
#tracing_enabled: true
#tracing_host: localhost:4317
#tracing_insecure: true
#tracing_cert_file: server-cert.pem
#tracing_key_file: server-key.pem

### Matrix

# Hostname of the Matrix Server
matrix_host: messenger.chain4travel.com

# Local DB file to store Matrix data
matrix_store: distributor-matrix.db

# Timeout in milliseconds to wait for responses on Matrix Server
response_timeout: 10000

### Bot RPC Configuration

# Listen on this port for RPC requests from the partner plugin (or Postman during
# development)
rpc_server_port: 9090
# TLS configuration
rpc_server_unencrypted: true
rpc_server_cert_file: server-cert.pem
rpc_server_key_file: server-key.pem

### Partner Plugin (NOT USED FOR DISTRIBUTOR BOT)
# Partner Plugin hostname and port, should be reachable from this machine.
#
# Bot tries to connect to this host and port to relay messages that it receives from
# the distributors through Matrix Server
#partner_plugin_host: localhost
#partner_plugin_port: 50051
# TLS configuration
#partner_plugin_unencrypted: true
# Required if partner_plugin_unencrypted is false
#partner_plugin_ca_file: ca-cert.pem

### C-Chain (EVM)

# Used for signing transactions on the c-chain, also used to log in into Matrix. This
# address needs to have some funds to pay for transaction fees on the C-Chain. This
# should be in hex format without the 0x prefix.
bot_key: YOUR_PRIVATE_KEY_HEX

# C-Chain RPC URL
chain_rpc_url: wss://columbus.camino.network/ext/bc/C/ws

# matrix application service bot address
network_fee_recipient_bot_address: 0xff6BAC3d972680515cbB59fCB6Db6deB13Eb0E91

# matrix application service cm account address
network_fee_recipient_cm_account: 0xF6bA5c68A505559c170dC7a30448Ed64D8b9Bc3B

cheque_expiration_time: 18144000 # 7 months

min_cheque_duration_until_expiration: 15552000 # 6 months

cash_in_period: 86400 # 1 day

### Booking Token

# Booking Token contract address. This address will be used for minting, buying of Booking Tokens
booking_token_address: "0xe55E387F5474a012D1b048155E25ea78C7DBfBBC"

# Address of the CM Account that the bot belongs to
cm_account_address: 0xYOUR_CM_ACCOUNT_ADDRESS


### Database

# Database name.
db_name: camino_messenger_bot

# Path to database file.
db_path: distributor-bot.db

# Path to migrations dir with sql up/down scripts. Schema is mandatory.
migrations_path: file://./migrations