# This example is made for development purposes - for production see docker-compose.yml



### General

# Lower level logging for local development
developer_mode: true

# Timeout in milliseconds to wait for responses to message sent via Matrix
response_timeout: 10000

# Booking Token contract address. This address will be used for minting, buying of Booking Tokens
booking_token_address: 0xe55E387F5474a012D1b048155E25ea78C7DBfBBC

# C-Chain RPC URL
chain_rpc_url: wss://columbus.camino.network/ext/bc/C/ws



### Bot identity

# Private key of the bot in hex format without the 0x prefix.
# Used for signing transactions on the c-chain, also used to log in into Matrix. This
# address needs to have some funds to pay for transaction fees on the C-Chain.
bot_key: YOUR_PRIVATE_KEY_HEX

# Address of the CM Account that the bot belongs to
cm_account_address: 0xYOUR_CM_ACCOUNT_ADDRESS



### Cheque handling

cheque_expiration_time: 18144000 # 7 months

min_cheque_duration_until_expiration: 15552000 # 6 months

cash_in_period: 86400 # 1 day

# matrix application service bot address
network_fee_recipient_bot_address: 0xff6BAC3d972680515cbB59fCB6Db6deB13Eb0E91

# matrix application service cm account address
network_fee_recipient_cm_account: 0xF6bA5c68A505559c170dC7a30448Ed64D8b9Bc3B



### Database
db:
  # Path to migrations dir with sql up/down scripts. Schema is mandatory.
  migrations_path: file://./migrations

  # Database name.
  name: camino_messenger_bot

  # Path to database file.
  path: distributor-bot.db



### Matrix
matrix:
  # Hostname of the Matrix server
  host: messenger.chain4travel.com

  # Local DB file to store Matrix data
  store: distributor-matrix.db



### Partner Plugin (NOT USED FOR DISTRIBUTOR BOT)
# partner_plugin:
#   # Partner Plugin hostname and port, should be reachable from this machine.
#   # Bot tries to connect to this host and port to relay messages that it receives from
#   # the distributors through Matrix Server
#   host: localhost:50051

#   # TLS configuration
#   unencrypted: true

#   # Required if partner_plugin_unencrypted is false
#   ca_file: ca-cert.pem



### RPC server
rpc_server:
  # Listen on this port for incoming RPC requests
  port: 9090

  # TLS configuration
  unencrypted: true

  cert_file: server-cert.pem
  key_file: server-key.pem



### Tracing
# tracing:
#   cert_file: server-cert.pem
#   enabled: true
#   host: localhost:4317
#   insecure: true
#   key_file: server-key.pem
