// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: flight_search.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlightSearchServiceClient is the client API for FlightSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightSearchServiceClient interface {
	Search(ctx context.Context, in *FlightSearchRequest, opts ...grpc.CallOption) (*FlightSearchResponse, error)
}

type flightSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightSearchServiceClient(cc grpc.ClientConnInterface) FlightSearchServiceClient {
	return &flightSearchServiceClient{cc}
}

func (c *flightSearchServiceClient) Search(ctx context.Context, in *FlightSearchRequest, opts ...grpc.CallOption) (*FlightSearchResponse, error) {
	out := new(FlightSearchResponse)
	err := c.cc.Invoke(ctx, "/messages.FlightSearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightSearchServiceServer is the server API for FlightSearchService service.
// All implementations must embed UnimplementedFlightSearchServiceServer
// for forward compatibility
type FlightSearchServiceServer interface {
	Search(context.Context, *FlightSearchRequest) (*FlightSearchResponse, error)
	mustEmbedUnimplementedFlightSearchServiceServer()
}

// UnimplementedFlightSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFlightSearchServiceServer struct {
}

func (UnimplementedFlightSearchServiceServer) Search(context.Context, *FlightSearchRequest) (*FlightSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedFlightSearchServiceServer) mustEmbedUnimplementedFlightSearchServiceServer() {}

// UnsafeFlightSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightSearchServiceServer will
// result in compilation errors.
type UnsafeFlightSearchServiceServer interface {
	mustEmbedUnimplementedFlightSearchServiceServer()
}

func RegisterFlightSearchServiceServer(s grpc.ServiceRegistrar, srv FlightSearchServiceServer) {
	s.RegisterService(&FlightSearchService_ServiceDesc, srv)
}

func _FlightSearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightSearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.FlightSearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightSearchServiceServer).Search(ctx, req.(*FlightSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightSearchService_ServiceDesc is the grpc.ServiceDesc for FlightSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messages.FlightSearchService",
	HandlerType: (*FlightSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _FlightSearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flight_search.proto",
}
