// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"context"
	"errors"
	"fmt"
	
	"github.com/chain4travel/camino-messenger-bot/v12/internal/messaging/message"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/rpc"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/version"

	{{TYPE_PACKAGE}} "{{PROTO_INC}}"
	typesv{{COMMON_TYPES_VERSION}} "buf.build/gen/go/chain4travel/camino-messenger-protocol/protocolbuffers/go/cmp/types/v{{COMMON_TYPES_VERSION}}"

	"buf.build/go/protovalidate"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func (s *{{SERVICE}}V{{VERSION}}Client) Call(ctx context.Context, requestIntf protoreflect.ProtoMessage, opts ...grpc.CallOption) (protoreflect.ProtoMessage, message.Type) {
	messageType := {{SERVICE}}ServiceV{{VERSION}}Response

	request, ok := requestIntf.(*{{TYPE_PACKAGE}}.{{REQUEST}})
	if !ok {
		return s.errorResponse(typesv{{COMMON_TYPES_VERSION}}.ErrorCode_ERROR_CODE_INTERNAL, fmt.Sprintf("invalid request type: expected %s, got %T", {{SERVICE}}ServiceV{{VERSION}}Request, requestIntf)), messageType
	}
	
	response, err := s.client.{{METHOD}}(ctx, request, opts...)
	switch {
	case errors.Is(err, rpc.ErrInvalidProto):
		return s.errorResponse(typesv{{COMMON_TYPES_VERSION}}.ErrorCode_ERROR_CODE_INVALID_PROTO, err.Error()), messageType
	case errors.Is(err, rpc.ErrBlockchain):
		return s.errorResponse(typesv{{COMMON_TYPES_VERSION}}.ErrorCode_ERROR_CODE_BLOCKCHAIN_ERROR, err.Error()), messageType
	case errors.Is(err, rpc.ErrBusinessProcess):
		return s.errorResponse(typesv{{COMMON_TYPES_VERSION}}.ErrorCode_ERROR_CODE_BUSINESS_PROCESS_ERROR, err.Error()), messageType
	case err != nil:
		return s.errorResponse(typesv{{COMMON_TYPES_VERSION}}.ErrorCode_ERROR_CODE_INTERNAL, err.Error()), messageType
	}

	if err := protovalidate.Validate(response); err != nil {
		return s.errorResponse(typesv{{COMMON_TYPES_VERSION}}.ErrorCode_ERROR_CODE_INVALID_PROTO, fmt.Sprintf("response validation failed: %v", err)), messageType
	}

	if errResp := response.GetErrorResponse(); errResp != nil {
		errResp.Header.BaseHeader.Version = version.VersionV4
	} else {
		response.GetSuccessResponse().Header.BaseHeader.Version = version.VersionV4
	}

	return response, messageType
}

func (s *{{SERVICE}}V{{VERSION}}Client) InvalidProtoErrResponseAndType(errorMessage string) (protoreflect.ProtoMessage, message.Type) {
	return s.errorResponse(typesv{{COMMON_TYPES_VERSION}}.ErrorCode_ERROR_CODE_INVALID_PROTO, errorMessage), {{SERVICE}}ServiceV{{VERSION}}Response
}

func (s *{{SERVICE}}V{{VERSION}}Client) errorResponse(code typesv{{COMMON_TYPES_VERSION}}.ErrorCode, errorMessage string) *{{TYPE_PACKAGE}}.{{RESPONSE}} {
	return &{{TYPE_PACKAGE}}.{{RESPONSE}}{
		Response: &{{TYPE_PACKAGE}}.{{RESPONSE}}_ErrorResponse{
			ErrorResponse: &{{TYPE_PACKAGE}}.{{SERVICE}}ErrorResponse{
				Header: &typesv{{COMMON_TYPES_VERSION}}.ErrorResponseHeader{
					BaseHeader: &typesv{{COMMON_TYPES_VERSION}}.Header{Version: version.VersionV{{COMMON_TYPES_VERSION}}},
					Errors: []*typesv{{COMMON_TYPES_VERSION}}.Error{{
						Code:    code,
						Message: errorMessage,
					}},
				},
			},
		},
	}
}
