// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/v11/internal/messaging (interfaces: EncoderDecoder)
//
// Generated by this command:
//
//	mockgen -package=messaging -destination=internal/messaging/mock_encoder_decoder.go github.com/chain4travel/camino-messenger-bot/v11/internal/messaging EncoderDecoder
//

// Package messaging is a generated GoMock package.
package messaging

import (
	context "context"
	reflect "reflect"

	encryption "github.com/chain4travel/camino-messenger-bot/v11/internal/messaging/encryption"
	types "github.com/chain4travel/camino-messenger-bot/v11/internal/messaging/types"
	cheques "github.com/chain4travel/camino-messenger-bot/v11/pkg/cheques"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockEncoderDecoder is a mock of EncoderDecoder interface.
type MockEncoderDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockEncoderDecoderMockRecorder
}

// MockEncoderDecoderMockRecorder is the mock recorder for MockEncoderDecoder.
type MockEncoderDecoderMockRecorder struct {
	mock *MockEncoderDecoder
}

// NewMockEncoderDecoder creates a new mock instance.
func NewMockEncoderDecoder(ctrl *gomock.Controller) *MockEncoderDecoder {
	mock := &MockEncoderDecoder{ctrl: ctrl}
	mock.recorder = &MockEncoderDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncoderDecoder) EXPECT() *MockEncoderDecoderMockRecorder {
	return m.recorder
}

// DecodeAndVerifyMessage mocks base method.
func (m *MockEncoderDecoder) DecodeAndVerifyMessage(arg0 context.Context, arg1 *EncodedSignedMessage, arg2 common.Address) (*types.Message, *cheques.SignedCheque, encryption.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeAndVerifyMessage", arg0, arg1, arg2)
	ret0, _ := ret[0].(*types.Message)
	ret1, _ := ret[1].(*cheques.SignedCheque)
	ret2, _ := ret[2].(encryption.Key)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// DecodeAndVerifyMessage indicates an expected call of DecodeAndVerifyMessage.
func (mr *MockEncoderDecoderMockRecorder) DecodeAndVerifyMessage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeAndVerifyMessage", reflect.TypeOf((*MockEncoderDecoder)(nil).DecodeAndVerifyMessage), arg0, arg1, arg2)
}

// EncodeMessage mocks base method.
func (m *MockEncoderDecoder) EncodeMessage(arg0 context.Context, arg1 *types.Message, arg2 *cheques.SignedCheque, arg3 common.Address, arg4 encryption.Key) (*EncodedSignedMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeMessage", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*EncodedSignedMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncodeMessage indicates an expected call of EncodeMessage.
func (mr *MockEncoderDecoderMockRecorder) EncodeMessage(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeMessage", reflect.TypeOf((*MockEncoderDecoder)(nil).EncodeMessage), arg0, arg1, arg2, arg3, arg4)
}
