// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/v13/internal/messaging (interfaces: Messenger)
//
// Generated by this command:
//
//	mockgen -package=messaging -destination=internal/messaging/mock_messenger.go github.com/chain4travel/camino-messenger-bot/v13/internal/messaging Messenger
//

// Package messaging is a generated GoMock package.
package messaging

import (
	context "context"
	reflect "reflect"

	cheques "github.com/chain4travel/camino-messenger-bot/v13/pkg/cheques"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockMessenger is a mock of Messenger interface.
type MockMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerMockRecorder
}

// MockMessengerMockRecorder is the mock recorder for MockMessenger.
type MockMessengerMockRecorder struct {
	mock *MockMessenger
}

// NewMockMessenger creates a new mock instance.
func NewMockMessenger(ctrl *gomock.Controller) *MockMessenger {
	mock := &MockMessenger{ctrl: ctrl}
	mock.recorder = &MockMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessenger) EXPECT() *MockMessengerMockRecorder {
	return m.recorder
}

// ReceivedMessageChan mocks base method.
func (m *MockMessenger) ReceivedMessageChan() chan EncodedSignedMessageWithSender {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceivedMessageChan")
	ret0, _ := ret[0].(chan EncodedSignedMessageWithSender)
	return ret0
}

// ReceivedMessageChan indicates an expected call of ReceivedMessageChan.
func (mr *MockMessengerMockRecorder) ReceivedMessageChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceivedMessageChan", reflect.TypeOf((*MockMessenger)(nil).ReceivedMessageChan))
}

// SendMessage mocks base method.
func (m *MockMessenger) SendMessage(arg0 context.Context, arg1 *EncodedSignedMessage, arg2 common.Address, arg3 *cheques.SignedCheque) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessengerMockRecorder) SendMessage(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessenger)(nil).SendMessage), arg0, arg1, arg2, arg3)
}

// Start mocks base method.
func (m *MockMessenger) Start(arg0 context.Context) (chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(chan error)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockMessengerMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockMessenger)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockMessenger) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockMessengerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockMessenger)(nil).Stop))
}
