// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/v13/internal/messaging (interfaces: ResponseHandler)
//
// Generated by this command:
//
//	mockgen -package=messaging -destination=internal/messaging/mock_response_handler.go github.com/chain4travel/camino-messenger-bot/v13/internal/messaging ResponseHandler
//

// Package messaging is a generated GoMock package.
package messaging

import (
	context "context"
	reflect "reflect"

	message "github.com/chain4travel/camino-messenger-bot/v13/internal/messaging/message"
	gomock "go.uber.org/mock/gomock"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// MockResponseHandler is a mock of ResponseHandler interface.
type MockResponseHandler struct {
	ctrl     *gomock.Controller
	recorder *MockResponseHandlerMockRecorder
}

// MockResponseHandlerMockRecorder is the mock recorder for MockResponseHandler.
type MockResponseHandlerMockRecorder struct {
	mock *MockResponseHandler
}

// NewMockResponseHandler creates a new mock instance.
func NewMockResponseHandler(ctrl *gomock.Controller) *MockResponseHandler {
	mock := &MockResponseHandler{ctrl: ctrl}
	mock.recorder = &MockResponseHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseHandler) EXPECT() *MockResponseHandlerMockRecorder {
	return m.recorder
}

// PrepareRequest mocks base method.
func (m *MockResponseHandler) PrepareRequest(arg0 protoreflect.ProtoMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrepareRequest", arg0)
}

// PrepareRequest indicates an expected call of PrepareRequest.
func (mr *MockResponseHandlerMockRecorder) PrepareRequest(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareRequest", reflect.TypeOf((*MockResponseHandler)(nil).PrepareRequest), arg0)
}

// PrepareResponseMessage mocks base method.
func (m *MockResponseHandler) PrepareResponseMessage(arg0 context.Context, arg1, arg2 *message.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrepareResponseMessage", arg0, arg1, arg2)
}

// PrepareResponseMessage indicates an expected call of PrepareResponseMessage.
func (mr *MockResponseHandlerMockRecorder) PrepareResponseMessage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareResponseMessage", reflect.TypeOf((*MockResponseHandler)(nil).PrepareResponseMessage), arg0, arg1, arg2)
}

// ProcessResponseMessage mocks base method.
func (m *MockResponseHandler) ProcessResponseMessage(arg0 context.Context, arg1, arg2 *message.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessResponseMessage", arg0, arg1, arg2)
}

// ProcessResponseMessage indicates an expected call of ProcessResponseMessage.
func (mr *MockResponseHandlerMockRecorder) ProcessResponseMessage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessResponseMessage", reflect.TypeOf((*MockResponseHandler)(nil).ProcessResponseMessage), arg0, arg1, arg2)
}
