// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: types/flight_search_criteria.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlightSearchCriteria struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepartureDate *Date  `protobuf:"bytes,1,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	Departure     string `protobuf:"bytes,2,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival       string `protobuf:"bytes,3,opt,name=arrival,proto3" json:"arrival,omitempty"`
	MinTime       string `protobuf:"bytes,4,opt,name=min_time,json=minTime,proto3" json:"min_time,omitempty"`
	MaxTime       string `protobuf:"bytes,5,opt,name=max_time,json=maxTime,proto3" json:"max_time,omitempty"`
}

func (x *FlightSearchCriteria) Reset() {
	*x = FlightSearchCriteria{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_criteria_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightSearchCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightSearchCriteria) ProtoMessage() {}

func (x *FlightSearchCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_criteria_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightSearchCriteria.ProtoReflect.Descriptor instead.
func (*FlightSearchCriteria) Descriptor() ([]byte, []int) {
	return file_types_flight_search_criteria_proto_rawDescGZIP(), []int{0}
}

func (x *FlightSearchCriteria) GetDepartureDate() *Date {
	if x != nil {
		return x.DepartureDate
	}
	return nil
}

func (x *FlightSearchCriteria) GetDeparture() string {
	if x != nil {
		return x.Departure
	}
	return ""
}

func (x *FlightSearchCriteria) GetArrival() string {
	if x != nil {
		return x.Arrival
	}
	return ""
}

func (x *FlightSearchCriteria) GetMinTime() string {
	if x != nil {
		return x.MinTime
	}
	return ""
}

func (x *FlightSearchCriteria) GetMaxTime() string {
	if x != nil {
		return x.MaxTime
	}
	return ""
}

type FlightOfferCriteria struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CabinCriteria   *CabinCriteria   `protobuf:"bytes,1,opt,name=cabin_criteria,json=cabinCriteria,proto3" json:"cabin_criteria,omitempty"`
	ServiceCriteria *ServiceCriteria `protobuf:"bytes,2,opt,name=service_criteria,json=serviceCriteria,proto3" json:"service_criteria,omitempty"`
}

func (x *FlightOfferCriteria) Reset() {
	*x = FlightOfferCriteria{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_criteria_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightOfferCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightOfferCriteria) ProtoMessage() {}

func (x *FlightOfferCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_criteria_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightOfferCriteria.ProtoReflect.Descriptor instead.
func (*FlightOfferCriteria) Descriptor() ([]byte, []int) {
	return file_types_flight_search_criteria_proto_rawDescGZIP(), []int{1}
}

func (x *FlightOfferCriteria) GetCabinCriteria() *CabinCriteria {
	if x != nil {
		return x.CabinCriteria
	}
	return nil
}

func (x *FlightOfferCriteria) GetServiceCriteria() *ServiceCriteria {
	if x != nil {
		return x.ServiceCriteria
	}
	return nil
}

type CabinCriteria struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CabinType    *CabinType      `protobuf:"bytes,1,opt,name=cabin_type,json=cabinType,proto3" json:"cabin_type,omitempty"`
	SeatCriteria []*SeatCriteria `protobuf:"bytes,2,rep,name=seat_criteria,json=seatCriteria,proto3" json:"seat_criteria,omitempty"`
	RowNumber    int32           `protobuf:"varint,3,opt,name=row_number,json=rowNumber,proto3" json:"row_number,omitempty"`
}

func (x *CabinCriteria) Reset() {
	*x = CabinCriteria{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_criteria_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CabinCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CabinCriteria) ProtoMessage() {}

func (x *CabinCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_criteria_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CabinCriteria.ProtoReflect.Descriptor instead.
func (*CabinCriteria) Descriptor() ([]byte, []int) {
	return file_types_flight_search_criteria_proto_rawDescGZIP(), []int{2}
}

func (x *CabinCriteria) GetCabinType() *CabinType {
	if x != nil {
		return x.CabinType
	}
	return nil
}

func (x *CabinCriteria) GetSeatCriteria() []*SeatCriteria {
	if x != nil {
		return x.SeatCriteria
	}
	return nil
}

func (x *CabinCriteria) GetRowNumber() int32 {
	if x != nil {
		return x.RowNumber
	}
	return 0
}

type CabinType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassOfServiceCode        string `protobuf:"bytes,1,opt,name=class_of_service_code,json=classOfServiceCode,proto3" json:"class_of_service_code,omitempty"`
	ClassOfServiceDescription string `protobuf:"bytes,2,opt,name=class_of_service_description,json=classOfServiceDescription,proto3" json:"class_of_service_description,omitempty"`
}

func (x *CabinType) Reset() {
	*x = CabinType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_criteria_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CabinType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CabinType) ProtoMessage() {}

func (x *CabinType) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_criteria_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CabinType.ProtoReflect.Descriptor instead.
func (*CabinType) Descriptor() ([]byte, []int) {
	return file_types_flight_search_criteria_proto_rawDescGZIP(), []int{3}
}

func (x *CabinType) GetClassOfServiceCode() string {
	if x != nil {
		return x.ClassOfServiceCode
	}
	return ""
}

func (x *CabinType) GetClassOfServiceDescription() string {
	if x != nil {
		return x.ClassOfServiceDescription
	}
	return ""
}

type SeatCriteria struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatType []*SeatType `protobuf:"bytes,1,rep,name=seat_type,json=seatType,proto3" json:"seat_type,omitempty"`
}

func (x *SeatCriteria) Reset() {
	*x = SeatCriteria{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_criteria_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatCriteria) ProtoMessage() {}

func (x *SeatCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_criteria_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatCriteria.ProtoReflect.Descriptor instead.
func (*SeatCriteria) Descriptor() ([]byte, []int) {
	return file_types_flight_search_criteria_proto_rawDescGZIP(), []int{4}
}

func (x *SeatCriteria) GetSeatType() []*SeatType {
	if x != nil {
		return x.SeatType
	}
	return nil
}

type SeatType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *SeatType) Reset() {
	*x = SeatType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_criteria_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatType) ProtoMessage() {}

func (x *SeatType) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_criteria_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatType.ProtoReflect.Descriptor instead.
func (*SeatType) Descriptor() ([]byte, []int) {
	return file_types_flight_search_criteria_proto_rawDescGZIP(), []int{5}
}

func (x *SeatType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SeatType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ServiceCriteria struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meal         bool                `protobuf:"varint,1,opt,name=meal,proto3" json:"meal,omitempty"`
	SpecialNeeds *ServiceSpecialNeed `protobuf:"bytes,2,opt,name=special_needs,json=specialNeeds,proto3" json:"special_needs,omitempty"`
}

func (x *ServiceCriteria) Reset() {
	*x = ServiceCriteria{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_criteria_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCriteria) ProtoMessage() {}

func (x *ServiceCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_criteria_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCriteria.ProtoReflect.Descriptor instead.
func (*ServiceCriteria) Descriptor() ([]byte, []int) {
	return file_types_flight_search_criteria_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceCriteria) GetMeal() bool {
	if x != nil {
		return x.Meal
	}
	return false
}

func (x *ServiceCriteria) GetSpecialNeeds() *ServiceSpecialNeed {
	if x != nil {
		return x.SpecialNeeds
	}
	return nil
}

type ServiceSpecialNeed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ServiceSpecialNeed) Reset() {
	*x = ServiceSpecialNeed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_criteria_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceSpecialNeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSpecialNeed) ProtoMessage() {}

func (x *ServiceSpecialNeed) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_criteria_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSpecialNeed.ProtoReflect.Descriptor instead.
func (*ServiceSpecialNeed) Descriptor() ([]byte, []int) {
	return file_types_flight_search_criteria_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceSpecialNeed) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServiceSpecialNeed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_types_flight_search_criteria_proto protoreflect.FileDescriptor

var file_types_flight_search_criteria_proto_rawDesc = []byte{
	0x0a, 0x22, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x10, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01,
	0x0a, 0x14, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x12, 0x32, 0x0a, 0x0e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x75, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x72, 0x69,
	0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76,
	0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x61, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x13, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x12, 0x3b, 0x0a, 0x0e, 0x63, 0x61, 0x62, 0x69, 0x6e, 0x5f, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x43, 0x61, 0x62, 0x69, 0x6e, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x52, 0x0d,
	0x63, 0x61, 0x62, 0x69, 0x6e, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x12, 0x41, 0x0a,
	0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x52,
	0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x22, 0x99, 0x01, 0x0a, 0x0d, 0x43, 0x61, 0x62, 0x69, 0x6e, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x12, 0x2f, 0x0a, 0x0a, 0x63, 0x61, 0x62, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43,
	0x61, 0x62, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x63, 0x61, 0x62, 0x69, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x63, 0x72, 0x69, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x52,
	0x0c, 0x73, 0x65, 0x61, 0x74, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x72, 0x6f, 0x77, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x7f, 0x0a, 0x09,
	0x43, 0x61, 0x62, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x15, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4f,
	0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x3f, 0x0a, 0x1c,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x19, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4f, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a,
	0x0c, 0x53, 0x65, 0x61, 0x74, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x12, 0x2c, 0x0a,
	0x09, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x08, 0x73, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x40, 0x0a, 0x08, 0x53,
	0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x65, 0x0a,
	0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x6d, 0x65, 0x61, 0x6c, 0x12, 0x3e, 0x0a, 0x0d, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x5f,
	0x6e, 0x65, 0x65, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69,
	0x61, 0x6c, 0x4e, 0x65, 0x65, 0x64, 0x52, 0x0c, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x4e,
	0x65, 0x65, 0x64, 0x73, 0x22, 0x4a, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x4e, 0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x34, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2f, 0x63, 0x61, 0x6d, 0x69,
	0x6e, 0x6f, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2d, 0x62, 0x6f, 0x74,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_flight_search_criteria_proto_rawDescOnce sync.Once
	file_types_flight_search_criteria_proto_rawDescData = file_types_flight_search_criteria_proto_rawDesc
)

func file_types_flight_search_criteria_proto_rawDescGZIP() []byte {
	file_types_flight_search_criteria_proto_rawDescOnce.Do(func() {
		file_types_flight_search_criteria_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_flight_search_criteria_proto_rawDescData)
	})
	return file_types_flight_search_criteria_proto_rawDescData
}

var file_types_flight_search_criteria_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_types_flight_search_criteria_proto_goTypes = []interface{}{
	(*FlightSearchCriteria)(nil), // 0: types.FlightSearchCriteria
	(*FlightOfferCriteria)(nil),  // 1: types.FlightOfferCriteria
	(*CabinCriteria)(nil),        // 2: types.CabinCriteria
	(*CabinType)(nil),            // 3: types.CabinType
	(*SeatCriteria)(nil),         // 4: types.SeatCriteria
	(*SeatType)(nil),             // 5: types.SeatType
	(*ServiceCriteria)(nil),      // 6: types.ServiceCriteria
	(*ServiceSpecialNeed)(nil),   // 7: types.ServiceSpecialNeed
	(*Date)(nil),                 // 8: types.Date
}
var file_types_flight_search_criteria_proto_depIdxs = []int32{
	8, // 0: types.FlightSearchCriteria.departure_date:type_name -> types.Date
	2, // 1: types.FlightOfferCriteria.cabin_criteria:type_name -> types.CabinCriteria
	6, // 2: types.FlightOfferCriteria.service_criteria:type_name -> types.ServiceCriteria
	3, // 3: types.CabinCriteria.cabin_type:type_name -> types.CabinType
	4, // 4: types.CabinCriteria.seat_criteria:type_name -> types.SeatCriteria
	5, // 5: types.SeatCriteria.seat_type:type_name -> types.SeatType
	7, // 6: types.ServiceCriteria.special_needs:type_name -> types.ServiceSpecialNeed
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_types_flight_search_criteria_proto_init() }
func file_types_flight_search_criteria_proto_init() {
	if File_types_flight_search_criteria_proto != nil {
		return
	}
	file_types_date_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_types_flight_search_criteria_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightSearchCriteria); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_criteria_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightOfferCriteria); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_criteria_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CabinCriteria); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_criteria_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CabinType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_criteria_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatCriteria); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_criteria_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_criteria_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceCriteria); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_criteria_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceSpecialNeed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_flight_search_criteria_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_flight_search_criteria_proto_goTypes,
		DependencyIndexes: file_types_flight_search_criteria_proto_depIdxs,
		MessageInfos:      file_types_flight_search_criteria_proto_msgTypes,
	}.Build()
	File_types_flight_search_criteria_proto = out.File
	file_types_flight_search_criteria_proto_rawDesc = nil
	file_types_flight_search_criteria_proto_goTypes = nil
	file_types_flight_search_criteria_proto_depIdxs = nil
}
