// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: types/flight_search_option.proto

package types

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Search Option
//
// This is for basic property search response's search options
type FlightSearchOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OfferId           string              `protobuf:"bytes,2,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Segments          []*FlightSegment    `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	Price             *Price              `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	AnciliaryServices []*AnciliaryService `protobuf:"bytes,5,rep,name=anciliary_services,json=anciliaryServices,proto3" json:"anciliary_services,omitempty"`
	Validity          *Validity           `protobuf:"bytes,6,opt,name=validity,proto3" json:"validity,omitempty"`
	CancelPolicy      *CancelPolicy       `protobuf:"bytes,7,opt,name=cancel_policy,json=cancelPolicy,proto3" json:"cancel_policy,omitempty"`
}

func (x *FlightSearchOption) Reset() {
	*x = FlightSearchOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_option_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightSearchOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightSearchOption) ProtoMessage() {}

func (x *FlightSearchOption) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_option_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightSearchOption.ProtoReflect.Descriptor instead.
func (*FlightSearchOption) Descriptor() ([]byte, []int) {
	return file_types_flight_search_option_proto_rawDescGZIP(), []int{0}
}

func (x *FlightSearchOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlightSearchOption) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *FlightSearchOption) GetSegments() []*FlightSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *FlightSearchOption) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *FlightSearchOption) GetAnciliaryServices() []*AnciliaryService {
	if x != nil {
		return x.AnciliaryServices
	}
	return nil
}

func (x *FlightSearchOption) GetValidity() *Validity {
	if x != nil {
		return x.Validity
	}
	return nil
}

func (x *FlightSearchOption) GetCancelPolicy() *CancelPolicy {
	if x != nil {
		return x.CancelPolicy
	}
	return nil
}

type FlightSegment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegmentId                 string          `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Airline                   string          `protobuf:"bytes,2,opt,name=airline,proto3" json:"airline,omitempty"`
	Departure                 *FlightSchedule `protobuf:"bytes,3,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival                   *FlightSchedule `protobuf:"bytes,4,opt,name=arrival,proto3" json:"arrival,omitempty"`
	ClassOfServiceDescription string          `protobuf:"bytes,5,opt,name=class_of_service_description,json=classOfServiceDescription,proto3" json:"class_of_service_description,omitempty"`
	ClassOfServiceCode        string          `protobuf:"bytes,6,opt,name=class_of_service_code,json=classOfServiceCode,proto3" json:"class_of_service_code,omitempty"`
	Price                     *Price          `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *FlightSegment) Reset() {
	*x = FlightSegment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_option_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightSegment) ProtoMessage() {}

func (x *FlightSegment) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_option_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightSegment.ProtoReflect.Descriptor instead.
func (*FlightSegment) Descriptor() ([]byte, []int) {
	return file_types_flight_search_option_proto_rawDescGZIP(), []int{1}
}

func (x *FlightSegment) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *FlightSegment) GetAirline() string {
	if x != nil {
		return x.Airline
	}
	return ""
}

func (x *FlightSegment) GetDeparture() *FlightSchedule {
	if x != nil {
		return x.Departure
	}
	return nil
}

func (x *FlightSegment) GetArrival() *FlightSchedule {
	if x != nil {
		return x.Arrival
	}
	return nil
}

func (x *FlightSegment) GetClassOfServiceDescription() string {
	if x != nil {
		return x.ClassOfServiceDescription
	}
	return ""
}

func (x *FlightSegment) GetClassOfServiceCode() string {
	if x != nil {
		return x.ClassOfServiceCode
	}
	return ""
}

func (x *FlightSegment) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

type FlightSchedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date    string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Airport string `protobuf:"bytes,2,opt,name=airport,proto3" json:"airport,omitempty"`
}

func (x *FlightSchedule) Reset() {
	*x = FlightSchedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_option_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightSchedule) ProtoMessage() {}

func (x *FlightSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_option_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightSchedule.ProtoReflect.Descriptor instead.
func (*FlightSchedule) Descriptor() ([]byte, []int) {
	return file_types_flight_search_option_proto_rawDescGZIP(), []int{2}
}

func (x *FlightSchedule) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FlightSchedule) GetAirport() string {
	if x != nil {
		return x.Airport
	}
	return ""
}

type AnciliaryService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price     *Price `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *AnciliaryService) Reset() {
	*x = AnciliaryService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_option_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnciliaryService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnciliaryService) ProtoMessage() {}

func (x *AnciliaryService) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_option_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnciliaryService.ProtoReflect.Descriptor instead.
func (*AnciliaryService) Descriptor() ([]byte, []int) {
	return file_types_flight_search_option_proto_rawDescGZIP(), []int{3}
}

func (x *AnciliaryService) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *AnciliaryService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnciliaryService) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

type Validity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *Validity) Reset() {
	*x = Validity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_flight_search_option_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validity) ProtoMessage() {}

func (x *Validity) ProtoReflect() protoreflect.Message {
	mi := &file_types_flight_search_option_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validity.ProtoReflect.Descriptor instead.
func (*Validity) Descriptor() ([]byte, []int) {
	return file_types_flight_search_option_proto_rawDescGZIP(), []int{4}
}

func (x *Validity) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Validity) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

var File_types_flight_search_option_proto protoreflect.FileDescriptor

var file_types_flight_search_option_proto_rawDesc = []byte{
	0x0a, 0x20, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x02, 0x0a, 0x12, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x73, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x46, 0x0a, 0x12, 0x61, 0x6e, 0x63, 0x69, 0x6c, 0x69, 0x61, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x41, 0x6e, 0x63, 0x69, 0x6c, 0x69, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x11, 0x61, 0x6e, 0x63, 0x69, 0x6c, 0x69, 0x61, 0x72, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x52, 0x08, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x69, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x0d, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x52, 0x0c, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0xc6,
	0x02, 0x0a, 0x0d, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2f,
	0x0a, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x12,
	0x3f, 0x0a, 0x1c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4f, 0x66, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x31, 0x0a, 0x15, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x12, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4f, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x69, 0x0a, 0x10, 0x41, 0x6e, 0x63, 0x69, 0x6c,
	0x69, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x22, 0x32, 0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x34, 0x74, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x2f, 0x63, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67,
	0x65, 0x72, 0x2d, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_flight_search_option_proto_rawDescOnce sync.Once
	file_types_flight_search_option_proto_rawDescData = file_types_flight_search_option_proto_rawDesc
)

func file_types_flight_search_option_proto_rawDescGZIP() []byte {
	file_types_flight_search_option_proto_rawDescOnce.Do(func() {
		file_types_flight_search_option_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_flight_search_option_proto_rawDescData)
	})
	return file_types_flight_search_option_proto_rawDescData
}

var file_types_flight_search_option_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_types_flight_search_option_proto_goTypes = []interface{}{
	(*FlightSearchOption)(nil), // 0: types.FlightSearchOption
	(*FlightSegment)(nil),      // 1: types.FlightSegment
	(*FlightSchedule)(nil),     // 2: types.FlightSchedule
	(*AnciliaryService)(nil),   // 3: types.AnciliaryService
	(*Validity)(nil),           // 4: types.Validity
	(*Price)(nil),              // 5: types.Price
	(*CancelPolicy)(nil),       // 6: types.CancelPolicy
}
var file_types_flight_search_option_proto_depIdxs = []int32{
	1, // 0: types.FlightSearchOption.segments:type_name -> types.FlightSegment
	5, // 1: types.FlightSearchOption.price:type_name -> types.Price
	3, // 2: types.FlightSearchOption.anciliary_services:type_name -> types.AnciliaryService
	4, // 3: types.FlightSearchOption.validity:type_name -> types.Validity
	6, // 4: types.FlightSearchOption.cancel_policy:type_name -> types.CancelPolicy
	2, // 5: types.FlightSegment.departure:type_name -> types.FlightSchedule
	2, // 6: types.FlightSegment.arrival:type_name -> types.FlightSchedule
	5, // 7: types.FlightSegment.price:type_name -> types.Price
	5, // 8: types.AnciliaryService.price:type_name -> types.Price
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_types_flight_search_option_proto_init() }
func file_types_flight_search_option_proto_init() {
	if File_types_flight_search_option_proto != nil {
		return
	}
	file_types_price_proto_init()
	file_types_cancel_policy_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_types_flight_search_option_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightSearchOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_option_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightSegment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_option_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightSchedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_option_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnciliaryService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_flight_search_option_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_flight_search_option_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_flight_search_option_proto_goTypes,
		DependencyIndexes: file_types_flight_search_option_proto_depIdxs,
		MessageInfos:      file_types_flight_search_option_proto_msgTypes,
	}.Build()
	File_types_flight_search_option_proto = out.File
	file_types_flight_search_option_proto_rawDesc = nil
	file_types_flight_search_option_proto_goTypes = nil
	file_types_flight_search_option_proto_depIdxs = nil
}
