// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: types/price.proto

package types

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Price
type Price struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency Currency `protobuf:"varint,1,opt,name=currency,proto3,enum=types.Currency" json:"currency,omitempty"`
	Net      float32  `protobuf:"fixed32,2,opt,name=net,proto3" json:"net,omitempty"`
	Gross    float32  `protobuf:"fixed32,3,opt,name=gross,proto3" json:"gross,omitempty"`
	Binding  bool     `protobuf:"varint,4,opt,name=binding,proto3" json:"binding,omitempty"`
	Concept  string   `protobuf:"bytes,5,opt,name=concept,proto3" json:"concept,omitempty"` // FIXME: Can this be an enum?
	// We can use a single price to represent a price breakdown
	Breakdown []*Price `protobuf:"bytes,6,rep,name=breakdown,proto3" json:"breakdown,omitempty"`
}

func (x *Price) Reset() {
	*x = Price{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_price_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_types_price_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_types_price_proto_rawDescGZIP(), []int{0}
}

func (x *Price) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_UNSPECIFIED_CURRENCY
}

func (x *Price) GetNet() float32 {
	if x != nil {
		return x.Net
	}
	return 0
}

func (x *Price) GetGross() float32 {
	if x != nil {
		return x.Gross
	}
	return 0
}

func (x *Price) GetBinding() bool {
	if x != nil {
		return x.Binding
	}
	return false
}

func (x *Price) GetConcept() string {
	if x != nil {
		return x.Concept
	}
	return ""
}

func (x *Price) GetBreakdown() []*Price {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

var File_types_price_proto protoreflect.FileDescriptor

var file_types_price_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x14, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xbc, 0x01, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6e, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x63, 0x65, 0x70, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x63,
	0x65, 0x70, 0x74, 0x12, 0x2a, 0x0a, 0x09, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x64, 0x6f, 0x77, 0x6e,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x52, 0x09, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x42,
	0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x34, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2f, 0x63, 0x61, 0x6d, 0x69, 0x6e,
	0x6f, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2d, 0x62, 0x6f, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_price_proto_rawDescOnce sync.Once
	file_types_price_proto_rawDescData = file_types_price_proto_rawDesc
)

func file_types_price_proto_rawDescGZIP() []byte {
	file_types_price_proto_rawDescOnce.Do(func() {
		file_types_price_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_price_proto_rawDescData)
	})
	return file_types_price_proto_rawDescData
}

var file_types_price_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_price_proto_goTypes = []interface{}{
	(*Price)(nil), // 0: types.Price
	(Currency)(0), // 1: types.Currency
}
var file_types_price_proto_depIdxs = []int32{
	1, // 0: types.Price.currency:type_name -> types.Currency
	0, // 1: types.Price.breakdown:type_name -> types.Price
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_price_proto_init() }
func file_types_price_proto_init() {
	if File_types_price_proto != nil {
		return
	}
	file_types_currency_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_types_price_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Price); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_price_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_price_proto_goTypes,
		DependencyIndexes: file_types_price_proto_depIdxs,
		MessageInfos:      file_types_price_proto_msgTypes,
	}.Build()
	File_types_price_proto = out.File
	file_types_price_proto_rawDesc = nil
	file_types_price_proto_goTypes = nil
	file_types_price_proto_depIdxs = nil
}
