package config

const (
	BookingTokenAddressKey                 = "booking_token_address"
	DeveloperMode                          = "developer_mode"
	EvmPrivateKey                          = "evm_private_key"
	RPCURLKey                              = "rpc_url"
	MatrixKey                              = "matrix_key"
	MatrixHost                             = "matrix_host"
	MatrixStore                            = "matrix_store"
	NetworkFeeRecipientBotAddressKey       = "network_fee_recipient_bot_address"
	NetworkFeeRecipientCMAccountAddressKey = "network_fee_recipient_cm_account"
	ChequeExpirationTimeKey                = "cheque_expiration_time"
	CMAccountAddressKey                    = "cm_account_address"
	RPCServerPortKey                       = "rpc_server_port"
	RPCUnencryptedKey                      = "rpc_unencrypted"
	RPCServerCertFileKey                   = "rpc_server_cert_file"
	RPCServerKeyFileKey                    = "rpc_server_key_file"
	PartnerPluginHostKey                   = "partner_plugin_host"
	PartnerPluginPortKey                   = "partner_plugin_port"
	PartnerPluginUnencryptedKey            = "partner_plugin_unencrypted"
	PartnerPluginCAFileKey                 = "partner_plugin_ca_file"
	MessengerTimeoutKey                    = "response_timeout"
	TracingEnabledKey                      = "tracing_enabled"
	TracingHostKey                         = "tracing_host"
	TracingPortKey                         = "tracing_port"
	TracingInsecureKey                     = "tracing_insecure"
	TracingCertFileKey                     = "tracing_cert_file"
	TracingKeyFileKey                      = "tracing_key_file"
	DBNameKey                              = "db_name"
	DBPathKey                              = "db_path"
	MigrationsPathKey                      = "migrations_path"
	MinChequeDurationUntilExpirationKey    = "min_cheque_duration_until_expiration"
	CashInPeriodKey                        = "cash_in_period"
)
