// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package server

import (
	"{{GRPC_INC}}"
	
	"google.golang.org/grpc"
)

var _ {{GRPC_PACKAGE}}.{{SERVICE}}Server = (*{{TYPE_PACKAGE}}_srv1)(nil)

type {{TYPE_PACKAGE}}_srv struct {
	reqProcessor externalRequestProcessor
}

func New{{SERVICE}}Server(
	grpcServer *grpc.Server,
	reqProcess externalRequestProcessor,
) {{GRPC_PACKAGE}}.{{SERVICE}}Server {
	{{TYPE_PACKAGE}}_srv := &{{TYPE_PACKAGE}}_srv1{reqProcessor: reqProcess}
	{{GRPC_PACKAGE}}.Register{{SERVICE}}Server(grpcServer, {{TYPE_PACKAGE}}_srv)
	return {{TYPE_PACKAGE}}_srv
}
