// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/v13/internal/resolver (interfaces: Resolver)
//
// Generated by this command:
//
//	mockgen -package=resolver -destination=internal/resolver/mock_resolver.go github.com/chain4travel/camino-messenger-bot/v13/internal/resolver Resolver
//

// Package resolver is a generated GoMock package.
package resolver

import (
	context "context"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockResolver is a mock of Resolver interface.
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance.
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// GetBotAddress mocks base method.
func (m *MockResolver) GetBotAddress(arg0 context.Context, arg1 common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBotAddress", arg0, arg1)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBotAddress indicates an expected call of GetBotAddress.
func (mr *MockResolverMockRecorder) GetBotAddress(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBotAddress", reflect.TypeOf((*MockResolver)(nil).GetBotAddress), arg0, arg1)
}

// SetBotStatus mocks base method.
func (m *MockResolver) SetBotStatus(arg0 context.Context, arg1 common.Address, arg2 BotStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBotStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBotStatus indicates an expected call of SetBotStatus.
func (mr *MockResolverMockRecorder) SetBotStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBotStatus", reflect.TypeOf((*MockResolver)(nil).SetBotStatus), arg0, arg1, arg2)
}
