// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/v12/internal/messaging/encoding (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -package=encoding -destination=internal/messaging/encoding/mock_storage.go github.com/chain4travel/camino-messenger-bot/v12/internal/messaging/encoding Storage
//

// Package encoding is a generated GoMock package.
package encoding

import (
	context "context"
	ecdsa "crypto/ecdsa"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Abort mocks base method.
func (m *MockStorage) Abort(arg0 Session) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Abort", arg0)
}

// Abort indicates an expected call of Abort.
func (mr *MockStorageMockRecorder) Abort(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abort", reflect.TypeOf((*MockStorage)(nil).Abort), arg0)
}

// Commit mocks base method.
func (m *MockStorage) Commit(arg0 Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockStorageMockRecorder) Commit(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockStorage)(nil).Commit), arg0)
}

// GetBotPubKey mocks base method.
func (m *MockStorage) GetBotPubKey(arg0 context.Context, arg1 Session, arg2 common.Address) (*ecdsa.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBotPubKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*ecdsa.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBotPubKey indicates an expected call of GetBotPubKey.
func (mr *MockStorageMockRecorder) GetBotPubKey(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBotPubKey", reflect.TypeOf((*MockStorage)(nil).GetBotPubKey), arg0, arg1, arg2)
}

// NewSession mocks base method.
func (m *MockStorage) NewSession(arg0 context.Context) (Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", arg0)
	ret0, _ := ret[0].(Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSession indicates an expected call of NewSession.
func (mr *MockStorageMockRecorder) NewSession(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockStorage)(nil).NewSession), arg0)
}

// SetBotPubKey mocks base method.
func (m *MockStorage) SetBotPubKey(arg0 context.Context, arg1 Session, arg2 common.Address, arg3 *ecdsa.PublicKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBotPubKey", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBotPubKey indicates an expected call of SetBotPubKey.
func (mr *MockStorageMockRecorder) SetBotPubKey(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBotPubKey", reflect.TypeOf((*MockStorage)(nil).SetBotPubKey), arg0, arg1, arg2, arg3)
}
