// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"context"
	"fmt"

	{{TYPE_PACKAGE}} "{{PROTO_INC}}"
	typesv{{COMMON_TYPES_VERSION}} "buf.build/gen/go/chain4travel/camino-messenger-protocol/protocolbuffers/go/cmp/types/v{{COMMON_TYPES_VERSION}}"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/messaging/types"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/rpc"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/version"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func (s {{SERVICE}}V{{VERSION}}Client) Call(ctx context.Context, requestIntf protoreflect.ProtoMessage, opts ...grpc.CallOption) (protoreflect.ProtoMessage, types.MessageType, error) {
	request, ok := requestIntf.(*{{TYPE_PACKAGE}}.{{REQUEST}})
	if !ok {
		return nil, {{SERVICE}}V{{VERSION}}Response, fmt.Errorf("invalid request type")
	}
	
	response, err := s.client.{{METHOD}}(ctx, request, opts...)

	// we need those check for pre-protovalidate cmp versions
	if response.Header == nil { // Header must be present, so errors can be added to it
		response.Header = &typesv{{COMMON_TYPES_VERSION}}.ResponseHeader{
			BaseHeader: &typesv{{COMMON_TYPES_VERSION}}.Header{},
		}
		if err == nil {
			err = rpc.ErrNilResponseHeader
		}
	}
	if response.Header.BaseHeader == nil { // BaseHeader must be present, so version can be set
		response.Header.BaseHeader =  &typesv{{COMMON_TYPES_VERSION}}.Header{}
		if err == nil {
			err = rpc.ErrNilResponseHeader
		}
	}

	response.Header.BaseHeader.Version = version.VersionV{{COMMON_TYPES_VERSION}}

	return response, {{SERVICE}}V{{VERSION}}Response, err
}
