// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"{{GRPC_INC}}"
	"github.com/chain4travel/camino-messenger-bot/internal/rpc"

	"google.golang.org/grpc"
)

var _ rpc.Client = (*{{SERVICE}}V{{VERSION}}Client)(nil)

func New{{SERVICE}}V{{VERSION}}(grpcCon *grpc.ClientConn) *{{SERVICE}}V{{VERSION}}Client {
	client := {{GRPC_PACKAGE}}.New{{SERVICE}}Client(grpcCon)
	return &{{SERVICE}}V{{VERSION}}Client{client: client}
}

type {{SERVICE}}V{{VERSION}}Client struct {
	client {{GRPC_PACKAGE}}.{{SERVICE}}Client
}
