// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"context"
	"fmt"

	{{TYPE_PACKAGE}} "{{PROTO_INC}}"
	typesv{{COMMON_TYPES_VERSION}} "buf.build/gen/go/chain4travel/camino-messenger-protocol/protocolbuffers/go/cmp/types/v{{COMMON_TYPES_VERSION}}"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/messaging/types"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/rpc"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/version"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func (s {{SERVICE}}V{{VERSION}}Client) Call(ctx context.Context, requestIntf protoreflect.ProtoMessage, opts ...grpc.CallOption) (protoreflect.ProtoMessage, types.MessageType, error) {
	messageType := {{SERVICE}}V{{VERSION}}Response

	request, ok := requestIntf.(*{{TYPE_PACKAGE}}.{{REQUEST}})
	if !ok {
		return s.errorResponse(fmt.Sprintf("invalid request type: expected %s, got %T", {{SERVICE}}V{{VERSION}}Request, requestIntf)), messageType, nil
	}
	
	response, err := s.client.{{METHOD}}(ctx, request, opts...)
	
	switch {
		case err != nil:
			return s.errorResponse(err.Error()), messageType, nil
		case response.GetHeader().GetBaseHeader() == nil:
			return s.errorResponse(rpc.ErrNilResponseHeader.Error()), messageType, nil
	}

	response.Header.BaseHeader.Version = version.VersionV{{COMMON_TYPES_VERSION}}

	return response, messageType, err
}

func (s *{{SERVICE}}V{{VERSION}}Client) ErrorResponseAndType(errorMessage string) (protoreflect.ProtoMessage, types.MessageType) {
	return s.errorResponse(errorMessage), {{SERVICE}}V{{VERSION}}Response
}

func (s *{{SERVICE}}V{{VERSION}}Client) errorResponse(errorMessage string) protoreflect.ProtoMessage {
	return &{{TYPE_PACKAGE}}.{{RESPONSE}}{
		Header: &typesv{{COMMON_TYPES_VERSION}}.ResponseHeader{
			BaseHeader: &typesv{{COMMON_TYPES_VERSION}}.Header{Version: version.VersionV{{COMMON_TYPES_VERSION}}},
			Status: typesv{{COMMON_TYPES_VERSION}}.StatusType_STATUS_TYPE_FAILURE,
			Alerts: []*typesv{{COMMON_TYPES_VERSION}}.Alert{{
				Message: errorMessage,
				Type:    typesv{{COMMON_TYPES_VERSION}}.AlertType_ALERT_TYPE_ERROR,
			}},
		},
	}
}
