// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"{{GRPC_INC}}"
	"github.com/chain4travel/camino-messenger-bot/internal/messaging/types"

	"google.golang.org/grpc"
)

const (
	{{SERVICE}}V{{VERSION}} = "{{FQPN}}"
	{{SERVICE}}V{{VERSION}}Request  types.MessageType = types.MessageType({{SERVICE}}V{{VERSION}} + ".Request")
	{{SERVICE}}V{{VERSION}}Response types.MessageType = types.MessageType({{SERVICE}}V{{VERSION}} + ".Response")
)

var _ Client = (*{{SERVICE}}V{{VERSION}}Client)(nil)

func New{{SERVICE}}V{{VERSION}}(grpcCon *grpc.ClientConn) *{{SERVICE}}V{{VERSION}}Client {
	client := {{GRPC_PACKAGE}}.New{{SERVICE}}Client(grpcCon)
	return &{{SERVICE}}V{{VERSION}}Client{client: &client}
}

type {{SERVICE}}V{{VERSION}}Client struct {
	client *{{GRPC_PACKAGE}}.{{SERVICE}}Client
}
