// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"context"
	"fmt"

	{{TYPE_PACKAGE}} "{{PROTO_INC}}"
)

func (s *{{TYPE_PACKAGE}}{{SERVICE}}Server) {{METHOD}}(ctx context.Context, request *{{TYPE_PACKAGE}}.{{REQUEST}}) (*{{TYPE_PACKAGE}}.{{RESPONSE}}, error) {
	response, err := s.reqHandler.HandleRequest(ctx, {{SERVICE}}V{{VERSION}}Request, request)
	if err != nil {
		return nil, fmt.Errorf("failed to process %s request: %w", {{SERVICE}}V{{VERSION}}Request, err)
	}
	resp, ok := response.(*{{TYPE_PACKAGE}}.{{RESPONSE}})
	if !ok {
		return nil, fmt.Errorf("invalid response type: expected %s, got %T", {{SERVICE}}V{{VERSION}}Response, response)
	}
	return resp, nil
}
