// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"{{GRPC_INC}}"
	"github.com/chain4travel/camino-messenger-bot/internal/rpc"
    "github.com/chain4travel/camino-messenger-bot/internal/messaging/types"

	"google.golang.org/grpc"
)

const (
	{{SERVICE}}V{{VERSION}} = "{{FQPN}}"
	{{SERVICE}}V{{VERSION}}Request  types.MessageType = types.MessageType({{SERVICE}}V{{VERSION}} + ".Request")
	{{SERVICE}}V{{VERSION}}Response types.MessageType = types.MessageType({{SERVICE}}V{{VERSION}} + ".Response")
)

var _ {{GRPC_PACKAGE}}.{{SERVICE}}Server = (*{{TYPE_PACKAGE}}{{SERVICE}}Server)(nil)

type {{TYPE_PACKAGE}}{{SERVICE}}Server struct {
	reqHandler rpc.RequestHandler
}

func register{{SERVICE}}V{{VERSION}}Server(grpcServer *grpc.Server, reqHandler rpc.RequestHandler) {
	{{GRPC_PACKAGE}}.Register{{SERVICE}}Server(grpcServer, &{{TYPE_PACKAGE}}{{SERVICE}}Server{reqHandler})
}
