// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"context"
	"fmt"

	"github.com/chain4travel/camino-messenger-bot/v12/internal/rpc"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/version"

	"buf.build/go/protovalidate"

	{{TYPE_PACKAGE}} "{{PROTO_INC}}"
)

func (s *{{TYPE_PACKAGE}}{{SERVICE}}Server) {{METHOD}}(ctx context.Context, request *{{TYPE_PACKAGE}}.{{REQUEST}}) (*{{TYPE_PACKAGE}}.{{RESPONSE}}, error) {
	if err := protovalidate.Validate(request); err != nil {
		return nil, fmt.Errorf("request validation failed: %w", err)
	}

	// we need this check for pre-protovalidate cmp versions
	// Header.BaseHeader must be present, so version can be set
	if request.Header.GetBaseHeader() == nil {
		return nil, rpc.ErrNilResponseHeader
	}

	request.Header.BaseHeader.Version = version.VersionV{{COMMON_TYPES_VERSION}}

	response, err := s.reqHandler.HandleMessageRequest(ctx, {{SERVICE}}V{{VERSION}}Request, request)
	if err != nil {
		return nil, fmt.Errorf("failed to process %s request: %w", {{SERVICE}}V{{VERSION}}Request, err)
	}

	resp, ok := response.(*{{TYPE_PACKAGE}}.{{RESPONSE}})
	if !ok {
		return nil, fmt.Errorf("invalid response type: expected %s, got %T", {{SERVICE}}V{{VERSION}}Response, response)
	}

	return resp, nil
}
