// Code generated by '{{GENERATOR}}'. DO NOT EDIT.
// template: {{TEMPLATE}}

package generated

import (
	"context"
	"fmt"

	"github.com/chain4travel/camino-messenger-bot/v12/internal/rpc"
	"github.com/chain4travel/camino-messenger-bot/v12/internal/version"

	"buf.build/go/protovalidate"

	typesv{{COMMON_TYPES_VERSION}} "buf.build/gen/go/chain4travel/camino-messenger-protocol/protocolbuffers/go/cmp/types/v{{COMMON_TYPES_VERSION}}"
	{{TYPE_PACKAGE}} "{{PROTO_INC}}"
)

func (s *{{TYPE_PACKAGE}}{{SERVICE}}Server) {{METHOD}}(ctx context.Context, request *{{TYPE_PACKAGE}}.{{REQUEST}}) (*{{TYPE_PACKAGE}}.{{RESPONSE}}, error) {
	if err := protovalidate.Validate(request); err != nil {
		return s.errorResponse(fmt.Sprintf("request validation failed: %v", err)), nil
	}

	// we need this check for pre-protovalidate cmp versions
	// Header.BaseHeader must be present, so version can be set
	if request.Header.GetBaseHeader() == nil {
		return s.errorResponse(rpc.ErrNilResponseHeader.Error()), nil
	}

	request.Header.BaseHeader.Version = version.VersionV{{COMMON_TYPES_VERSION}}

	responseIntf, err := s.reqHandler.HandleMessageRequest(ctx, {{SERVICE}}V{{VERSION}}Request, request)
	if err != nil {
		return s.errorResponse(err.Error()), nil
	}

	response, ok := responseIntf.(*{{TYPE_PACKAGE}}.{{RESPONSE}})
	if !ok {
		return s.errorResponse(fmt.Sprintf("invalid response type: expected %s, got %T", {{SERVICE}}V{{VERSION}}Response, response)), nil
	}

	return response, nil
}

func (s *{{TYPE_PACKAGE}}{{SERVICE}}Server) errorResponse(errorMessage string) *{{TYPE_PACKAGE}}.{{RESPONSE}} {
	return &{{TYPE_PACKAGE}}.{{RESPONSE}}{
		Header: &typesv{{COMMON_TYPES_VERSION}}.ResponseHeader{
			BaseHeader: &typesv{{COMMON_TYPES_VERSION}}.Header{Version: version.VersionV{{COMMON_TYPES_VERSION}}},
			Status: typesv{{COMMON_TYPES_VERSION}}.StatusType_STATUS_TYPE_FAILURE,
			Alerts: []*typesv{{COMMON_TYPES_VERSION}}.Alert{{
				Message: errorMessage,
				Type:    typesv{{COMMON_TYPES_VERSION}}.AlertType_ALERT_TYPE_ERROR,
			}},
		},
	}
}
