#!/bin/bash

BUF_SDK_BASE="buf.build/gen/go/chain4travel/camino-messenger-protocol"
TEMPLATES_DIR_BASE="templates"
P2P_OUTPATH="internal/rpc/generated"
LOCAL_OUTPATH="internal/rpc/generated"
E2E_GEN_OUTPATH="tests/e2e/bot/generated"

REGISTER_SERVICES_SERVER_FILE="${P2P_OUTPATH}/register_server_services.go"
REGISTER_SERVICES_CLIENT_FILE="${P2P_OUTPATH}/register_client_services.go"
UNMARSHALLING_FILE="${P2P_OUTPATH}/unmarshal.go"
E2E_BOT_CLIENT_FILE="${E2E_GEN_OUTPATH}/client.go"


DEFAULT_BLACKLIST="partner network claim notification insurance" # we don't want to generate handlers for notifications - if we ever need more filters here the impl. need to change!

SCRIPT=$(realpath --relative-to="${PWD}" "$0")
FILTER=$1 #optional filter for files -- used for testing

function generate_with_templates() {
	FQPN="$1"
	SERVICE="$2"
	GRPC_PACKAGE="$3"
	TYPE_PACKAGE="$4"
	local -n _METHODS=$5
	local -n _INPUTS=$6
	local -n _OUTPUTS=$7
	GRPC_INCLUDE="$8"
	PROTO_INCLUDE="$9"
	_VERSION="${10}"
	GENERATOR="${11}"
	COMMON_TYPES_VERSION="${12}"

	# From here on it's very easy in case it's just search replace
	# Simply copy the template to the target directory
	# And do some sed -i -e "s#{{.FQDN}}#$FQDN#g" -e "s#{{.SERVICE}}#$SERVICE#g" [...] $file
	GENERAL_PARAM_REPLACE=""
	GENERAL_PARAM_REPLACE+=" -e s#{{FQPN}}#$FQPN#g"
	GENERAL_PARAM_REPLACE+=" -e s#{{SERVICE}}#$SERVICE#g"
	GENERAL_PARAM_REPLACE+=" -e s#{{GRPC_PACKAGE}}#$GRPC_PACKAGE#g"
	GENERAL_PARAM_REPLACE+=" -e s#{{TYPE_PACKAGE}}#$TYPE_PACKAGE#g"
	GENERAL_PARAM_REPLACE+=" -e s#{{GRPC_INC}}#$GRPC_INCLUDE#g"
	GENERAL_PARAM_REPLACE+=" -e s#{{PROTO_INC}}#$PROTO_INCLUDE#g"
	GENERAL_PARAM_REPLACE+=" -e s#{{VERSION}}#$_VERSION#g"
	GENERAL_PARAM_REPLACE+=" -e s#{{GENERATOR}}#$GENERATOR#g"
	GENERAL_PARAM_REPLACE+=" -e s#{{COMMON_TYPES_VERSION}}#$COMMON_TYPES_VERSION#g"
	GENERAL_PARAM_REPLACE+=" -e s#{{EMPTY_IMPORT}}#$EMPTY_IMPORT#g"

	## This is added to fix shellcheck issue SC2086
	replace_params=()
	eval "replace_params+=( $GENERAL_PARAM_REPLACE )"

    EMPTY_IMPORT=""
	# Generate client and server code based on routing
	if [[ "$ROUTING" == "p2p" ]]; then
		# Generate client
		CLIENT_GEN_FILE="${P2P_OUTPATH}/${TYPE_PACKAGE}_${SERVICE}_client.go"
		echo "🔨 Generating client: $CLIENT_GEN_FILE"
		cp "$CLIENT_TEMPLATE" "$CLIENT_GEN_FILE"

		sed -i "${replace_params[@]}" "$CLIENT_GEN_FILE"
		sed -i -e "s#{{TEMPLATE}}#$CLIENT_TEMPLATE#g" "$CLIENT_GEN_FILE"

		# Generate client methods
		for num in $(seq 0 $(( ${#_METHODS[@]} - 1 ))) ; do
			METHOD=${_METHODS[$num]}
			INPUT=${_INPUTS[$num]}
			OUTPUT=${_OUTPUTS[$num]}
			METHOD_PARAM_REPLACE=""
			METHOD_PARAM_REPLACE+=" -e s#{{METHOD}}#$METHOD#g"
			METHOD_PARAM_REPLACE+=" -e s#{{REQUEST}}#$INPUT#g"
			METHOD_PARAM_REPLACE+=" -e s#{{RESPONSE}}#$OUTPUT#g"
			if [[ $OUTPUT == "Empty" ]]; then
				EMPTY_IMPORT='"google.golang.org/protobuf/types/known/emptypb"'
				TYPE_PACKAGE="emptypb"
			fi
			METHOD_GEN_FILE="${P2P_OUTPATH}/${TYPE_PACKAGE}_${SERVICE}_client_method.go"
			## This is added to fix shellcheck issue SC2086
			method_params=()
			eval "method_params+=( $METHOD_PARAM_REPLACE )"

			echo "🔨 Generating client method: $METHOD_GEN_FILE"
			cp "$CLIENT_METHOD_TEMPLATE" "$METHOD_GEN_FILE"
			sed -i "${replace_params[@]}" "$METHOD_GEN_FILE"
			sed -i "${method_params[@]}" "$METHOD_GEN_FILE"
			sed -i -e "s#{{TEMPLATE}}#$CLIENT_METHOD_TEMPLATE#g" "$METHOD_GEN_FILE"
		done

		# Generate server
		SERVER_GEN_FILE="${P2P_OUTPATH}/${TYPE_PACKAGE}_${SERVICE}_server.go"
		echo "🔨 Generating server: $SERVER_GEN_FILE"
		cp "$SERVER_TEMPLATE" "$SERVER_GEN_FILE"
		sed -i "${replace_params[@]}" "$SERVER_GEN_FILE"
		sed -i -e "s#{{TEMPLATE}}#$SERVER_TEMPLATE#g" "$SERVER_GEN_FILE"

	    EMPTY_IMPORT=""
		# Generate server methods
		for num in $(seq 0 $(( ${#_METHODS[@]} - 1 ))) ; do
			METHOD=${_METHODS[$num]}
			INPUT=${_INPUTS[$num]}
			OUTPUT=${_OUTPUTS[$num]}
			METHOD_PARAM_REPLACE=""
			METHOD_PARAM_REPLACE+=" -e s#{{METHOD}}#$METHOD#g"
			METHOD_PARAM_REPLACE+=" -e s#{{REQUEST}}#$INPUT#g"
			METHOD_PARAM_REPLACE+=" -e s#{{RESPONSE}}#$OUTPUT#g"
			if [[ $OUTPUT == "Empty" ]]; then
				EMPTY_IMPORT='"google.golang.org/protobuf/types/known/emptypb"'
				TYPE_PACKAGE="emptypb"
			fi
			METHOD_GEN_FILE="${P2P_OUTPATH}/${TYPE_PACKAGE}_${SERVICE}_server_method.go"

			## This is added to fix shellcheck issue SC2086
			method_params=()
			eval "method_params+=( $METHOD_PARAM_REPLACE )"

			echo "🔨 Generating server method: $METHOD_GEN_FILE"
			cp "$SERVER_P2P_METHOD_TEMPLATE" "$METHOD_GEN_FILE"
			sed -i "${replace_params[@]}" "$METHOD_GEN_FILE"
			sed -i "${method_params[@]}" "$METHOD_GEN_FILE"
			sed -i -e "s#{{TEMPLATE}}#$SERVER_P2P_METHOD_TEMPLATE#g" "$METHOD_GEN_FILE"
		done
	fi
}

function generate_register_services_server() {
	OUTFILE="$1"
	local -n _SERVICES=$2

	echo "📝 Registering server services in $OUTFILE"

	{
		echo "// Code generated by '${SCRIPT}'. DO NOT EDIT."
		echo
		echo "package generated"
		echo
		echo "import ("
		echo "    \"github.com/chain4travel/camino-messenger-bot/v12/internal/rpc\""
		echo "    \"google.golang.org/grpc\""
		echo ")"
		echo
		echo "func RegisterServerServices(grpcServer *grpc.Server, reqHandler rpc.RequestHandler) {"
		for service in "${_SERVICES[@]}" ; do
			echo "    register${service}Server(grpcServer, reqHandler)"
		done
		echo "}"
	} > "$OUTFILE"
}

function generate_register_services_client() {
	OUTFILE="$1"
	local -n _SERVICES=$2

	echo "📝 Registering client services in $OUTFILE"

	{
		echo "// Code generated by '${SCRIPT}'. DO NOT EDIT."
		echo
		echo "package generated"
		echo
		echo "import ("
		echo "    \"github.com/chain4travel/camino-messenger-bot/v12/internal/messaging/message\""
		echo "    \"github.com/chain4travel/camino-messenger-bot/v12/internal/rpc\""
		echo "    \"google.golang.org/grpc\""
		echo ")"
		echo
		echo "func RegisterServiceClients(rpcConn *grpc.ClientConn, serviceNames map[string]struct{}) map[message.Type]rpc.Service {"
		echo "    services := make(map[message.Type]rpc.Service, len(serviceNames))"
		echo
		for service in "${_SERVICES[@]}" ; do
			echo "    if _, ok := serviceNames[${service}]; ok {"
			echo "        services[${service}Request] = rpc.NewService(New${service}Client(rpcConn), ${service})"
			echo "        delete(serviceNames, ${service})"
			echo "    }"
		done
		echo "    return services"
		echo "}"
	} >> "$OUTFILE"
}

function generate_unmarshalling() {
	OUTFILE="$1"
	local -n _PROTO_INCLUDES=$2
	local -n _UNMARSHAL_METHODS=$3

	echo "📝 Generating unmarshalling in $OUTFILE"

	{
		echo "// Code generated by '${SCRIPT}'. DO NOT EDIT."
		echo
		echo "package generated"
		echo
		echo "import ("
		for include in "${_PROTO_INCLUDES[@]}" ; do
			echo "    \"${include}\""
		done
		echo "    \"github.com/chain4travel/camino-messenger-bot/v12/internal/messaging/message\""
		echo "    \"google.golang.org/protobuf/proto\""
		echo "    \"google.golang.org/protobuf/reflect/protoreflect\""
		echo ")"
		echo

		echo "func UnmarshalContent(src []byte, msgType message.Type, destination *protoreflect.ProtoMessage) error {"
		echo "    switch msgType {"

		for method in "${_UNMARSHAL_METHODS[@]}" ; do
			IFS=' ' read -r -a parts <<< "$method"
			echo "    case ${parts[0]}:"
			echo "        *destination = &${parts[1]}.${parts[2]}{}"
		done

		echo "    default:"
		echo "        return message.ErrUnknownMessageType"
		echo "    }"
		echo "    return proto.Unmarshal(src, *destination)"
		echo "}"
	} > "$OUTFILE"
}

function generate_e2e_bot_client() {
	OUTFILE="$1"
	local -n _GRPC_INCLUDES=$2
	local -n _PACKAGES=$3
	local -n _TYPES=$4
	local -n _FIELDS=$5

	declare -a _CLIENT_FIELDS=()
	declare -a _CLIENT_FIELDS_CONSTRUCTOR=()

	for field in "${_FIELDS[@]}" ; do
		_CLIENT_FIELDS+=("${field} ")
		_CLIENT_FIELDS_CONSTRUCTOR+=("${field}: ")
	done

	for i in "${!_PACKAGES[@]}" ; do
		_CLIENT_FIELDS[i]="${_CLIENT_FIELDS[$i]} ${_PACKAGES[$i]}.${_TYPES[$i]}"
		_CLIENT_FIELDS_CONSTRUCTOR[i]="${_CLIENT_FIELDS_CONSTRUCTOR[$i]} ${_PACKAGES[$i]}.New${_TYPES[$i]}(connection)"
	done


	echo "🔨📝 Generating E2E bot client $OUTFILE"

	{
		echo "// Code generated by '${SCRIPT}'. DO NOT EDIT."
		echo
		echo "package generated"
		echo
		echo "import ("
		for include in "${_GRPC_INCLUDES[@]}" ; do
			echo "    \"${include}\""
		done
		echo "    \"google.golang.org/grpc\""
		echo ")"
		echo
		echo "func NewClient(connection *grpc.ClientConn) *Client {"
		echo "    return &Client{"
		for field_constructor in "${_CLIENT_FIELDS_CONSTRUCTOR[@]}" ; do
			echo "        ${field_constructor},"
		done
		echo "    }"
		echo "}"
		echo "type Client struct {"
		for field in "${_CLIENT_FIELDS[@]}" ; do
			echo "    ${field}"
		done
		echo "}"
	} > "$OUTFILE"
}

# Prepare the output directories
echo "🧹 Cleaning and generating output directories"
rm -rf $P2P_OUTPATH
mkdir -p $P2P_OUTPATH
rm -rf $LOCAL_OUTPATH
mkdir -p $LOCAL_OUTPATH

BUF_GRPC_VERSION=$(grep -oP "buf.build/gen/go/chain4travel/camino-messenger-protocol/grpc/go.*" go.mod | cut -d" " -f2)
echo "🔗 Extracting SDK GRPC version from go.mod: $BUF_GRPC_VERSION"

BUF_PB_VERSION=$(grep -oP "buf.build/gen/go/chain4travel/camino-messenger-protocol/protocolbuffers/go.*" go.mod | cut -d" " -f2)
echo "🔗 Extracting SDK PB version from go.mod: $BUF_PB_VERSION"

BUF_SDK_URL_GO_GRPC="${BUF_SDK_BASE}/grpc/go"
echo "⌛ Downloading SDK ${BUF_GRPC_VERSION} from $BUF_SDK_URL_GO_GRPC"
go get "${BUF_SDK_URL_GO_GRPC}@${BUF_GRPC_VERSION}"

BUF_SDK_URL_GO_PB="${BUF_SDK_BASE}/protocolbuffers/go"
echo "⌛ Downloading SDK ${BUF_PB_VERSION} from ${BUF_SDK_URL_GO_PB}"
go get "${BUF_SDK_URL_GO_PB}@${BUF_PB_VERSION}"

echo "🔍 Searching for go path"
if [ -n "$GOPATH" ] ; then
	GO_PATH=$GOPATH
fi

if [ -z "$GO_PATH" ] ; then
	# no luck? extract it from go env!
	GO_PATH=$(go env | grep GOPATH | cut -d"'" -f2)
fi

if [ -z "$GO_PATH" ] ; then
	# still no luck?!
	# try out the defaults:
	if [ -f ~/.go ] ; then
		GO_PATH=~/.go
	elif [ -f ~/go ] ; then
		GO_PATH=~/go
	fi
fi

if [ -z "$GO_PATH" ] ; then
	echo "❌ Can't find go path :("
	exit 1
fi

SDK_GRPC_PATH="${GO_PATH}/pkg/mod/buf.build/gen/go/chain4travel/camino-messenger-protocol/grpc/go@${BUF_GRPC_VERSION}"
echo "SDK_GRPC_PATH: $SDK_GRPC_PATH"

SDK_PB_PATH="${GO_PATH}/pkg/mod/buf.build/gen/go/chain4travel/camino-messenger-protocol/protocolbuffers/go@${BUF_PB_VERSION}"
echo "SDK_PB_PATH: $SDK_PB_PATH"

echo "⌛ Making sure gofumpt is installed"
go install mvdan.cc/gofumpt@latest

FUMPT="${GO_PATH}/bin/gofumpt"
if [ ! -f "$FUMPT" ] ; then
	echo "❌ gofumpt not found at $FUMPT"
	exit 1
fi

declare -a SERVICES_TO_REGISTER=()
declare -a PROTO_INCLUDES_FOR_UNMARSHALLING=()
declare -a UNMARSHAL_METHODS=()
declare -a E2E_GRPC_INCLUDES=()
declare -a E2E_CLIENT_FIELDS=()
declare -a E2E_PACKAGES=()
declare -a E2E_TYPES=()

while read -r file ; do
	if [ -n "$FILTER" ] ; then
		if [[ ! $file =~ $FILTER ]] ; then
			continue
		fi
	fi

	for blacklisted in $DEFAULT_BLACKLIST ; do
		if [[ $file =~ $blacklisted ]] ; then
			echo "⚠️ Skipping (blacklisted): $file"
			echo
			continue 2
		fi
	done

	echo "🔍 Scanning file $file"

	# Extract the annotation line
	TAGS_LINE=$(grep -E '@custom:cmp-service' "$file")

	# Use shell parameter expansion to extract values
	SERVICE_TYPE=${TAGS_LINE#*type:}
	SERVICE_TYPE=${SERVICE_TYPE%% *}

	ROUTING=${TAGS_LINE#*routing:}
	ROUTING=${ROUTING%% *}

	ON_CHAIN=${TAGS_LINE#*on-chain:}
	ON_CHAIN=${ON_CHAIN%%[[:space:]]*}

    STRUCTURE=1
    if [[ $TAGS_LINE =~ structure:([0-9]+) ]]; then
        STRUCTURE="${BASH_REMATCH[1]}"
    fi
    TEMPLATES_DIR="${TEMPLATES_DIR_BASE}/v${STRUCTURE}"

    CLIENT_TEMPLATE="${TEMPLATES_DIR}/client.go.tpl"
    CLIENT_METHOD_TEMPLATE="${TEMPLATES_DIR}/client_method.go.tpl"
    SERVER_TEMPLATE="${TEMPLATES_DIR}/server.go.tpl"
    SERVER_P2P_METHOD_TEMPLATE="${TEMPLATES_DIR}/server_p2p_method.go.tpl"

	FQPN=$(grep -P 'FullMethodName' "$file" | grep -oP 'cmp\.services\.[^/]+' | head -n1) # only 1 - it may contain more
	SERVICE=${FQPN##*.}
	SERVICE=${SERVICE%Service}
	PACKAGE=$(grep -oP '^package \S+$' "$file" | cut -d" " -f2)
	TYPE=${PACKAGE%*grpc}
	VERSION=$(echo "$FQPN" | grep -oP "\.v[0-9]+\." | cut -d"." -f2 )
	PACKAGE_VERSION=${TYPE##*v}
	PACKAGE_NAME=${TYPE%v*}

	file_name=$(basename "$file")
	file_name_prefix=${file_name%_grpc.pb.go}
	pb_file="$SDK_PB_PATH/cmp/services/${PACKAGE_NAME}/v${PACKAGE_VERSION}/${file_name_prefix}.pb.go"

	if [ ! -f "$pb_file" ] ; then
		echo "❌ Can't find corresponding pb file (${pb_file}) for $file"
		exit 1
	fi

	COMMON_TYPES_VERSION=$(grep -oP '(?<=Header \*v)\d+(?=\.(?:Success)?ResponseHeader)' "$pb_file" | tail -n 1)

	echo "🔑 FQPN      : $FQPN"
	echo "⚙️ Service   : $SERVICE"
	echo "🏷️ Tags      : type=$SERVICE_TYPE, routing=$ROUTING, on-chain=$ON_CHAIN"
	echo "📦 Go Package: $PACKAGE"
	echo "🔧 Type      : $TYPE"

	echo "📑 Methods: "
	declare -a METHODS=()
	declare -a INPUTS=()
	declare -a OUTPUTS=()
	while IFS= read -r method
	do
		# Now we try to extract the inputs and outputs for each method
		# for this grep $method(xxx, INPUT) (OUTPUT, yyy)
		# strip out the version prefix (*vX.)Name

		PARAMS_CUT=$(grep -P "^\t${method}\(context.Context" "$file" | cut -d"," -f2 | tr -d '()')

		## This is added to fix shellcheck issue SC2086
		cut_params=()
		eval "cut_params+=( $PARAMS_CUT )"

		# This gives us " *stuff.INPUT *stuff.OUTPUT" -- let's get INPUT and OUTPUT separately
		INPUT=$(echo "${cut_params[@]}" | cut -d" " -f1 | cut -d"." -f2)
		OUTPUT=$(echo "${cut_params[@]}" | cut -d" " -f2 | cut -d"." -f2)

		METHODS+=("$method")
		INPUTS+=("$INPUT")
		OUTPUTS+=("$OUTPUT")

		# We need to pass something for the unmarshalling here
		# First we need the service name including the version plus if it's request or response
		# Then we need the package name
		# And finally Input and Output
		# So something like:
		# PingServiceV1Request pingv1 PingRequest
		# PingServiceV1Response pingv1 PingResponse
		if [[ "$ROUTING" == "p2p" ]]; then
			UNMARSHAL_METHODS+=("${SERVICE}ServiceV${VERSION:1}Request $TYPE $INPUT")
			UNMARSHAL_METHODS+=("${SERVICE}ServiceV${VERSION:1}Response $TYPE $OUTPUT")
		fi

		echo " ◉ $method (↓ in: '$INPUT' - ↑ out: '$OUTPUT')"
	done < <(grep -P 'FullMethodName' "$file" | grep -oP 'cmp\.services\.[^"]+' | cut -d"/" -f2)

	# We also need something like:
	# "buf.build/gen/go/chain4travel/camino-messenger-protocol/protocolbuffers/go/cmp/services/activity/v2"
	# "buf.build/gen/go/chain4travel/camino-messenger-protocol/grpc/go/cmp/services/activity/v2/activityv2grpc"
	# We already have the base URL in BUF_SDK_URL_GO_GRPC - now we only need the suffixes for the protocolbuffers and grpc
	# And store them into the PROTO_INCLUDES_FOR_UNMARSHALLING array
	# First the protocolbuffers
	SUFFIX=$(echo "${FQPN%.*}" | tr "." "/")
	PROTO_INCLUDE="${BUF_SDK_BASE}/protocolbuffers/go/${SUFFIX}"
	# Now the grpc which is quite similar by just adding the package name at the end
	GRPC_INCLUDE="${BUF_SDK_BASE}/grpc/go/${SUFFIX}/${PACKAGE}"
	generate_with_templates "$FQPN" "$SERVICE" "$PACKAGE" "$TYPE" METHODS INPUTS OUTPUTS "$GRPC_INCLUDE" "$PROTO_INCLUDE" "${VERSION:1}" "$SCRIPT" "$COMMON_TYPES_VERSION"

	E2E_GRPC_INCLUDES+=("$GRPC_INCLUDE")
	E2E_PACKAGES+=("$PACKAGE")
	E2E_TYPES+=("${SERVICE}ServiceClient")
	E2E_CLIENT_FIELDS+=("${SERVICE}ServiceV${VERSION:1}")

	if [[ "$ROUTING" == "p2p" ]]; then
		SERVICES_TO_REGISTER+=("${SERVICE}ServiceV${VERSION:1}")
		PROTO_INCLUDES_FOR_UNMARSHALLING+=("$PROTO_INCLUDE")
	fi

	echo
done < <(find "$SDK_GRPC_PATH/cmp/services/" -name "*_grpc.pb.go" | sort)

generate_register_services_server "$REGISTER_SERVICES_SERVER_FILE" SERVICES_TO_REGISTER
generate_register_services_client "$REGISTER_SERVICES_CLIENT_FILE" SERVICES_TO_REGISTER
generate_unmarshalling "$UNMARSHALLING_FILE" PROTO_INCLUDES_FOR_UNMARSHALLING UNMARSHAL_METHODS
generate_e2e_bot_client "$E2E_BOT_CLIENT_FILE" E2E_GRPC_INCLUDES E2E_PACKAGES E2E_TYPES E2E_CLIENT_FIELDS

echo "🧹 Running gofumpt on all generated files"
$FUMPT -w $P2P_OUTPATH
$FUMPT -w $LOCAL_OUTPATH
$FUMPT -w $E2E_GEN_OUTPATH
