// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chain4travel/camino-messenger-bot/v12/internal/common (interfaces: ResponseHeaderHandler)
//
// Generated by this command:
//
//	mockgen -package=common -destination=internal/common/mock_response_header.go github.com/chain4travel/camino-messenger-bot/v12/internal/common ResponseHeaderHandler
//

// Package common is a generated GoMock package.
package common

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// MockResponseHeaderHandler is a mock of ResponseHeaderHandler interface.
type MockResponseHeaderHandler struct {
	ctrl     *gomock.Controller
	recorder *MockResponseHeaderHandlerMockRecorder
}

// MockResponseHeaderHandlerMockRecorder is the mock recorder for MockResponseHeaderHandler.
type MockResponseHeaderHandlerMockRecorder struct {
	mock *MockResponseHeaderHandler
}

// NewMockResponseHeaderHandler creates a new mock instance.
func NewMockResponseHeaderHandler(ctrl *gomock.Controller) *MockResponseHeaderHandler {
	mock := &MockResponseHeaderHandler{ctrl: ctrl}
	mock.recorder = &MockResponseHeaderHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseHeaderHandler) EXPECT() *MockResponseHeaderHandlerMockRecorder {
	return m.recorder
}

// AddError mocks base method.
func (m *MockResponseHeaderHandler) AddError(arg0 protoreflect.ProtoMessage, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddError", arg0, arg1)
}

// AddError indicates an expected call of AddError.
func (mr *MockResponseHeaderHandlerMockRecorder) AddError(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddError", reflect.TypeOf((*MockResponseHeaderHandler)(nil).AddError), arg0, arg1)
}
