name: CI

on:
  pull_request:
    branches: [c4t, dev]
  workflow_dispatch:

# Cancel ongoing workflow runs if a new one is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  go_version: "~1.23.1"

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Update dependencies
        run: git submodule update --init
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
      - name: Install libolm
        run: sudo apt update && sudo apt-get install -y libolm-dev
      - name: build_test
        shell: bash
        run: ./scripts/build_test.sh
  # When the golangci-lint version is updated here, also update it in scripts/lint.sh
  lint:
    name: Static Analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Update dependencies
        run: git submodule update --init
      - name: Install libolm
        run: sudo apt update && sudo apt-get install -y libolm-dev
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          only-new-issues: true
  go_mod_tidy:
    name: Check state of go.mod and go.sum
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Update dependencies
        run: git submodule update --init
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
      - name: Go Mod Tidy
        shell: bash
        run: go mod tidy
      - name: Check Clean Branch
        shell: bash
        run: .github/workflows/check-clean-branch.sh
