name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_dockerhub:
    name: Push Docker image to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.event.release.tag_name }}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            c4tplatform/camino-messenger-bot:latest
            c4tplatform/camino-messenger-bot:${{ github.event.release.tag_name }}