name: Publish Release Artifcats

on:
  release:
    types: [published]

jobs:
  release:
    name: Publish Artifcats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.event.release.tag }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install libolm
        run: sudo apt update && sudo apt-get install -y libolm-dev
      
      - name: Build
        run: ./scripts/build.sh

      - name: upload release assets
        run: |
          tar -zcvf camino-messenger-bot-linux-amd64-${{ github.event.release.tag }}.tar.gz ./build/bot 
          gh release upload ${{ github.event.release.tag }} camino-messenger-bot-linux-amd64-${{ github.event.release.tag }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

