name: Publish Release Artifcats

on:
  release:
    types: [published]
  push:
    branches: [release-artifacts]

permissions:
  contents: write

jobs:
  release:
    name: Publish Artifcats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: v6.1.0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install libolm
        run: sudo apt update && sudo apt-get install -y libolm-dev
      
      - name: Build
        run: ./scripts/build.sh

      - name: upload release assets
        run: |
          tar -zcvf camino-messenger-bot-linux-amd64-v6.1.0.tar.gz ./build/bot 
          gh release upload v6.1.0 camino-messenger-bot-linux-amd64-v6.1.0.tar.gz
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

